TOPIC: String Based Assignment Problem

1. Write a program to reverse a string.

In [8]:
def reverse_string(string):
    reverse=''
    for i in string:
        reverse= i + reverse
    return reverse
        

string='Hello world!'
reverse_string(string)

'!dlrow olleH'

# Explanation:

* Creating a function called reverse_string and passing an argument called string
* Then i am creating a empty string called reverse, we will use this later.
* Creating a for loop  and iterating each letter from the string which is passed in the function argument.
* Passing the each letter from the iteration in to the variable reverse, which we already created and also concatenating the previous letter stored in the variable reverse, so that for every iteration when new letter adds  it will add before the stored letter so in the end it will give us the string in reverse format.
* Then using the return in function and returning the value of reverse variable.
* Finally assigning a value for string argument and calling the function reverse_string and passing the string variable.


2. Check if a string is a palindrome.

In [9]:
user_input=input("Enter the word ")
lower_sting=user_input.lower()
reverse_string=lower_sting[::-1]
if lower_sting == reverse_string:
    print(f'This word {user_input} is a palindrome')
else:
    print(f'This word {user_input} is a not palindrome')

Enter the word  Madam


This word Madam is a palindrome


# Explanation:

* Geting the word from the user using input() function.
* Changing all the letters from the word into lower case in order avoid any case sensetive issues.
* Reverse the word using the slicing method in string operation.
* Using the If else statement, if the lowered string matches the same letters in reverse sting index it will be palindrome so used a print() function to print the statement its a palindrome. If it doesn't match it will come into else statement and print its not a palindrome.

3. Convert a string to uppercase.

In [16]:
user_input=input("Enter the string ")
final_string= user_input.upper()
print(f"Your input : {user_input}, Converted String: {final_string}")

Enter the string  hello world!


Your input : hello world!, Converted String: HELLO WORLD!


# Explanation:

* Geting the string from the user using input() function.
* Using the string in-built function upper() to convert all the letters from the string into upper case and assigning into variable final_string.
* Printing the statement of user input and the final converted Upper string using the  f-string feature.

4. Convert a string to lowercase.

In [18]:
user_input=input("Enter the string ")
final_string= user_input.lower()
print(f"Your input : {user_input}, Converted String: {final_string}")

Enter the string  HOW ARE YOU.


Your input : HOW ARE YOU., Converted String: how are you.


# Explanation:

* Geting the string from the user using input() function.
* Using the string in-built function lower() to convert all the letters from the string into upper case and assigning into variable final_string.
* Printing the statement of user input and the final converted lower string using the  f-string feature.

5. Count the number of vowels in a string.

In [25]:
user_input=input("Enter the string") # taking the user input
lower_string=user_input.lower()  # using the lower built in function to lower case the letters
vowels=['a','e','i','o','u']  # vowels present in English Grammar
result=[]  
for i in lower_string:  #iterating the user input modified with lower keyword
    if i in vowels:  # checking if any letter from user input is in our vowels list, if it matches it will continue or else it will exit and return to loop
        result.append(i)  # appending the letter with matched in our empty result list
print('Vowels that are present in the string are: ', result)
print('Total number of vowels present in string is',len(result)) 

Enter the string Encyclopedia


Vowels that are present in the string are:  ['e', 'o', 'e', 'i', 'a']
Total number of vowels present in string is 5


# Explanation:

* Getting the input from user using the input() function
* Changing all the letters from the sentence into lower case in order to avoid the case sensetive issue while matching the letters.
* assigning the vowels strings into a list to a variable called vowels because we are going to use this to match with our user input string.
* Creating an empty list inorder to store the vowels which are going to match with our vowels input.
* Looping the lower_string using for loop statement and using the if class statement and in keyword inorder to find if any of the vowels strings from the variable is present in the lower_string, if any string matches it will be appended to our result list using the append built in function.
* Printing the Vowels present in the user input using print function and printing the count of the vowels present using len keyword.

6. Count the number of consonants in a string.

In [30]:
def consonants(string):
    lower_string=string.lower()  # using the lower built in function to lower case the letters
    vowels=['a','e','i','o','u']  # vowels present in English Grammar
    count=0
    for i in lower_string:  #iterating the user input modified with lower keyword
        if i not in vowels:  # checking if any letter from string is not in our vowels list, if it matches it will continue or else it will exit and return to loop
            count+=1  # adding 1 count for each successful strings not present in vowels.
    return count
string='Encyclopedia'
number_of_consonants= consonants(string)
print( f'Total number of consonants present in {string} is {number_of_consonants}.')

Total number of consonants present in Encyclopedia is 7.


# Explanation: 

* Consonants refer to the letters in the alphabet that are not vowels. Comparatively vowels count is lesser, hence i am using vowels to find the number of consonants present in the string.
* Creating a function called consonants with a argument string.
* Inside the function, first lowering the letters from string using the lower() in-built function. 
* Then assigning the values for vowels variable. This will later used in if statement.
* Creating a variable "count" with 0 value. Following, creating a for loop which iterates the lower_string variable we converted.
* Creating a condition if any letters from the lower_string is not matching with the vowels, then its a consonants, so i am adding 1 to the variable "count" which i created outside the loop. 
* Finally returning the count value from the consonants function.
* Creating an argument which needs to be passed in function. Calling the function with argument passed and assign its value into a variable called number_of_consonants.
* Lastly printing the passed string and its count of consonants using the f-string method.

7. Remove all whitespaces from a string.

In [44]:
def whitespace_removal(string):  # Creating a function with passing argument string
    final_string=""        # creating a variable with empty string for storing purpose
    for i in string:        # Looping the string passed as argument
        if i ==" ":             # creating if  condition if the i is a empty string need to pass it
            pass
        else:                   # if any string not passed the above condition and come to this else condition, then that string will add to our fina_string variable.
            final_string+=i
            
    return final_string

string= "               Hello,      How        are you  ,how is your day. "
whitespace_removal(string)

'Hello,Howareyou,howisyourday.'

# Explanatin: 

* Creating a function whitespace_removal with string as passing argument.
* Creating a variable with empty string to store the strings from the loop later.
* Creating a for loop and itertating the strings as i, then creating if  else condition where if any of the iterating string contains empty space then it will simply pass and if it failed to meet this condition and in the else part that iterating string will add into the final_string variable.
* Finally returning the final_string value from the function.
* Lastly creating a string variable and calling the whitespace_removal function by passing the string argument.

8. Find the length of a string without using the `len()` function.

In [50]:
def length(string):
    count=0
    for i in string:
        count+=1
    return count

result= length("Hello")
print('The length of the string is ',result)

The length of the string is  5


# Explanation: 

* Creating a function called length with takes single argument.
* Initializing a variable count with 0 value 
* Creating a for loop which iterates the string argument we pass in the function. For every iteration it will add 1 to the count variable we created earlier.
* Returning the count value in the function.
* Finally calling the length function and passing the string argument and assigning it to the variable result. Then printing the statement along with the length of the string counted.

9. Check if a string contains a specific word.

In [59]:
sentence = input('Enter the sentence: ')
word_wants_to_check = input("Enter the word you need to check in the sentence: ")

if word_wants_to_check in sentence:  #Check if the word_wants_to_check is present in the sentence using the 'in' keyword
    print(f"The string contains the word {word_wants_to_check}.")
else:
    print(f"The string does not contain the word {word_wants_to_check}.")

Enter the sentence:  Need to check a specific word
Enter the word you need to check in the sentence:  check


The string contains the word check.


# Explanation: 


* Getting the input from the user for sentence and the word he wants to check in that sentence using the input() in-built function.
* Then using the if else condition, If the specific word is found in the string, it prints a message indicating that the word is present. It uses an f-string to include the value of word_wants_to_check in the printed message.
* If the specific word is not found in the string, the program executes the code block under the else statement and prints the message the string not contains the word_wants_to_check.


10. Replace a word in a string with another word.

In [71]:
def word_replacement(sentence,old_word, replace_word):
    raplaced_sentence= sentence.replace(old_word,replace_word)
    return raplaced_sentence


sentence=input('Enter the sentence: ')
old_word=input('Enter the old word: ')
replace_word=input('Enter the replacement word: ')
word_replacement(sentence,old_word, replace_word)
    

Enter the sentence:  Largest planet in the solar-system is Mars
Enter the old word:  Mars
Enter the replacement word:  Jupiter


'Largest planet in the solar-system is Jupiter'

# Explanation: 

* Creating a function word_replacement taking 3 arguments sentence, old_word, replace_word
* using the replace() in-built function replacing the old word with replace word and assigning it to replaced_sentence variable, then returning the replaced_sentence value.
* Using the input() in-built function collecting the arguments which are needed to calling a function.
* Calling the word_replacement function and passing the arguments which are stored in variables entered by user. Now you will able to see the result with the replaced word





11. Count the occurrences of a word in a string.

In [134]:
def word_count(sentence, word_string):    # Creating a function taking 2 arguments
    lowered_sentence=sentence.lower()     # lowering the sentence using lower() function
    lowered_word_string=word_string.lower()   # lowering the word given by user using lower() function
    split_=lowered_sentence.split(" ")        # Splitting the lowered sentence using " " as seperator
    split_words=[word.rstrip('.,') for word in split_]   # using the list comprehension and removing the , and . which are not removed while splitting the words
    words=0                 # creating a variable with value 0 
    for word in split_words:           # Looping the splitted words 
        if word == lowered_word_string:    # if single word from iteration matches the user input 1 count will be added to word variable
            words+=1    
    return f'The word "{word_string}" occured {words} times.'   # returning the word variable and the word user want to check using f-string

In [136]:
# asking input from user
sentence=input("Enter the sentence: ")
word_string=input('Enter the word want to check the occurance: ')
word_count(sentence, word_string)  # calling the function

Enter the sentence:  Early in the morning, the birds chirped and the sun rose, creating a beautiful, beautiful day.
Enter the word want to check the occurance:  rose


'The word "rose" occured 1 times.'

# Explanation: 

* Creating a function  word_count taking 2 arguments as sentence, word_string
* Lowering the sentence and word_string passed inside the function using lower() function method.
* Splitting the lowered sentence using (" ") as seperator, then the list comprehension iterates through split words and removes trailing commas and fullstop from each word using rstrip('.,'). 
* Since there are chances the string from the user could contains the , and . it will leads to incorrect response while checking the word occurance if it is not removed. 
* Creating a variable with value 0 for counting the occurance purpose.
* Looping the splitted words, if single word from iteration matches the user input 1 count will be added to word variable which we created earlier.
* Returning the word variable and the word user want to check using f-string
* Using the input() in-built function collecting the arguments which are needed to calling a function.
* Calling the word_count function and passing the arguments which are stored in variables entered by user. Now you will able to see the result with the word count.


12. Find the first occurrence of a word in a string.

In [153]:
def first_occurrence(sentence, word):
    index = sentence.find(word)   # Find the index of the first occurrence using find() method.
    if index != -1: #Check if the index is not -1, indicating that the word was found.
        result = f"First occurrence of the {word} is {index}th index"
    else:
         result =( f"{word} is not found in the sentence")
    return result
sentence=input("Enter the sentence: ").lower()
word=input('Enter the word want to check the first occurance: ').lower()
first_occurrence(sentence, word)

Enter the sentence:  Early in the morning, the birds chirped and the sun rose, creating a beautiful, beautiful day.
Enter the word want to check the first occurance:  the


'First occurrence of the the is 9th index'

# Explanation:

* Creating a function first_occurrence taking 2 arguments as sentence, word
* Creating a index variable where i am using the find() in-built function in the sentence argument and passing the word argument inside the find function to find its index.
* Using the if else statement: As the find() inbuilt function return the index of the word we are passing, if that word is not present it will give us the -1 as result, so i am checking if that index is not equal to -1 that means that word is present and the index variable stores the correct index, I am using the f-string method and storing a statement of the first occurance word and its index in result variable.
* If the word input by the user is not found in the sentence, the block will move to else part and i am using the f-string method and storing a statement that "word is not found in the sentence" in a result variable.
* Returning the result variable
* Creating a input() in-built function and getting the sentence and from from user and storing it inside the sentence and word variable.
* Calling the function first_occurrence(sentence, word) passing the arguments we get from user input.

13. Find the last occurrence of a word in a string.

In [2]:
def last_occurrence(sentence, word):
    index = sentence.rfind(word)   # Find the index of the last occurrence using rfind() method which search from right to left.
    if index != -1: #Check if the index is not -1, indicating that the word was found.
        result = f"Last occurrence of the {word} is in index {index}."
    else:
         result =( f"{word} is not found in the sentence")
    return result
sentence=input("Enter the sentence: ").lower()
word=input('Enter the word want to check the Last occurance: ').lower()
last_occurrence(sentence, word)

Enter the sentence:  Hello, how is your day, how are you\
Enter the word want to check the Last occurance:  How


'Last occurrence of the how is in index 24.'

# Explanation:

* Creating a function last_occurrence taking 2 arguments as sentence, word
* Creating a index variable where i am using the rfind() in-built function in the sentence argument and passing the word argument inside the rfind function to find its index its start to check from right to left of a string.
* Using the if else statement: As the rfind() inbuilt function return the index of the word we are passing, if that word is not present it will give us the -1 as result, so i am checking if that index is not equal to -1 that means that word is present and the index variable stores the correct index, I am using the f-string method and storing a statement of the last occurance word and its index in result variable.
* If the word input by the user is not found in the sentence, the block will move to else part and i am using the f-string method and storing a statement that "word is not found in the sentence" in a result variable.
* Returning the result variable
* Creating a input() in-built function and getting the sentence and from from user and storing it inside the sentence and word variable.
* Calling the function last_occurrence(sentence, word) passing the arguments we get from user input.

14. Split a string into a list of words.

In [3]:
string= input('Enter the string ')
split_list= string.split()
print(split_list)

Enter the string  Hello how are you


['Hello', 'how', 'are', 'you']


# Explanation:

* Getting the input from user using the in-built input() function and storing it in string variable.
* Using the split() in-built function to split the string. Split function will split the sentence into list of words as its default split is spaces i am not specified it here and string it inside the variable split_list.
* Using the print function and printing the list of words.

15. Join a list of words into a string.

In [12]:
list_of_words= input("Input the list of words seperated by comma ")
converted_into_list=list_of_words.split(',') # using the split() function with , as seperator
combine_list = ' '.join(converted_into_list)  # using the join() function to join the list of words
combine_list

Input the list of words seperated by comma  Hello!, how, are , you.


'Hello!  how  are   you.'

# Explanation: 

* Getting the input from the user using input() in-built function and giving the user a hint to put the list of words seperated by comma and stored it in varibale list_of_words.
* Since the variable list_of_words is a string converting it into a list by splitting the string using split builtin function with the seperator comma in it.
* Now joining the list of words into a single string using the join() inbuilt function with space as seperator and storing it in the variable combined_list.
* printing the combined_list it will show the result in a single string value.

16. Convert a string where words are separated by spaces to one where words
are separated by underscores.

In [14]:
string= input("Input the list of words seperated by space ")
converted_into_list=string.split() # using the split() function with , as seperator
under_score_string = '_'.join(converted_into_list)  # using the join() function to join the list of words
under_score_string

Input the list of words seperated by space  Hello! how are you.


'Hello!_how_are_you.'

# Explanation: 

* Getting the input from the user using input() in-built function and giving the user a hint to put the list of words seperated by space and stored it in varibale string.
* Since the variable list_of_words is a string converting it into a list by splitting the string using split builtin function with the default space seperator.
* Now joining the list of words into a single string using the join() inbuilt function with '_' as seperator and storing it in the variable under_score_string.
* printing the under_score_string it will show the result in a single string value seperated by underscores.

17. Check if a string starts with a specific word or phrase.

In [1]:
def string_starts_with(text, prefix):
    start_with = text.startswith(prefix) #Use the startswith() method to check if the text starts with the specified prefix.
    if start_with == 1:
        result =f"The text starts with the prefix {prefix}."
    else:
        result =f"The text does not start with the prefix {prefix}."
    return result
text=input("Enter the text: ")
prefix= input("Enter the start word: ")
string_starts_with(text, prefix)

Enter the text:  Hello World
Enter the start word:  Hello


'The text starts with the prefix Hello.'

# Explanation: 

* Creating a function string_starts_with with two arguments text and prefix.
* Inside the function creating a variable start_with where using the builtin function. The startswith() method returns True if the string starts with the specified value, otherwise False. 
* Now using the if else statement and if our start_with == 1 which means start_with == True it will execute the code under the if statement, else move to the else block and execute the code on else. If "IF statement" is true i am storing a statement with use of f-string in result variable. If else is true doing the same with another statement.
* Returning the result variable.
* Getting the input from the user for text and prefix variables.
* Calling the string_starts_with function and passing the text and prefix arguments from user input

18. Check if a string ends with a specific word or phrase.

In [4]:
def string_ends_with(text, suffix):
    ends_with = text.endswith(suffix) #Use the startswith() method to check if the text starts with the specified prefix.
    if ends_with == 1:
        result = f"The text ends with the word - {suffix}."
    else:
        result = f"The text does not ends with the word - {suffix}."
    return result
text=input("Enter the text: ")
suffix= input("Enter the end word: ")
string_ends_with(text, suffix)

Enter the text:  Hello world
Enter the end word:  world


'The text ends with the word - world.'

# Explanation: 

* Creating a function string_ends_with with two arguments text and suffix.
* Inside the function creating a variable start_with where using the builtin function. The endswith() method returns True if the string ends with the specified value, otherwise False. 
* Now using the if else statement and if our ends_with == 1 which means ends_with == True it will execute the code under the if statement, else move to the else block and execute the code on else. If "IF statement" is true i am storing a statement with use of f-string in result variable. If else is true doing the same with another statement.
* Returning the result variable.
* Getting the input from the user for text and suffix variables.
* Calling the string_ends_with function and passing the text and suffix arguments from user input

19. Convert a string to title case (e.g., "hello world" to "Hello World").

In [1]:
string=input("Enter the string ")
title_case= string.title() # using the title method do convert first character in every word is upper case. 
print("Updated string: ",title_case)


Enter the string  hello world


Updated string:  Hello World


# Explanation:

* Getting the input from user using input function.
* Using the string operation in-built function title(). This method returns a string where the first character in every word is upper case. 
* Printing the variable to show the string with title case.

20. Find the longest word in a string.

In [33]:
string= input("Enter the string: ")
words= string.split()  # using the split() method to split the text into a list of words

word=''
longest_word_length = 0
for i in words:   # Iterate through the list of words.
    if len(i) > longest_word_length:
        longest_word_length = len(i)
        word =i
        
print(f"The longest word in the string is {word} and its length is {longest_word_length}.")
        
    

Enter the string:  Hello how is your Health condition


The longest word in the string is condition and its length is 9.


# Explanation: 

* Using the input() method and getting the string from user.
* using the split() method splitting the string from the user with space as a default seperator.
* Initializing two variables word and longest_word_length to hold the final output from the loop.
* Creating a for loop and iterate through the list of words. Using the inbuilt len() function and compare the length of the words iterating with the longest_word_length. If the length of the word is greater, longest_word_length is equal to the current word length and word is equal to current word.
* printing the final statement  of the longest word using f-string along with its length.

21. Find the shortest word in a string.

In [43]:
string= input("Enter the string: ")
words= string.split()  # using the split() method to split the text into a list of words

word=''
shortest_word_length = len(words[0])  # initialising the shorteste word with first word length
for i in words:   # Iterate through the list of words.
    if len(i) < shortest_word_length:
        shortest_word_length = len(i)
        word =i
        
print(f"The shortest word in the string is '{word}' and its length is {shortest_word_length}.")
        
    

Enter the string:  Hello how is your Health condition


The shortest word in the string is 'is' and its length is 2.


# Explanation: 

* Using the input() method and getting the string from user.
* using the split() method splitting the string from the user with space as a default seperator.
* Initializing two variables word and shortest_word_length to hold the final output from the loop. For shortest_word_length variable declaring the value of the length of the first word from the split words.
* Creating a for loop and iterate through the list of words. Using the inbuilt len() function and compare the length of the words iterating with the shortest_word_length. If the length of the word is lesser, shortest_word_length is equal to the current word length and word is equal to current word.
* printing the final statement  of the Shortest word using f-string along with its length.

22. Reverse the order of words in a string.

In [2]:
def reverse_word(string):
    words= string.split()  # Splitting the string into to list of words
    reverse= words[::-1]   # Reversing the order of words in the list
    join=' '.join(reverse)  # using join method to join the list of words into a single string
    return join

string= input("Enter the string: ")
reverse_word(string)

Enter the string:  Hello how are you


'you are how Hello'

# Explanation: 

* Creating a function named reverse_word where passing 1 argument string.
* Splitting the string into to list of words using the default space seperator 
* Reversing the order of words in the list using the negative indexing of -1 as step.
* Joining the reversed words with " ", using join method.
* Returning the join variable where we stored the final joined words.
* Getting the input from the user using the input() function and storing it in the string variable which we going to use for the function argument.
* Calling the function and passing the argument variable.

23. Check if a string is alphanumeric.

In [15]:
def alphanumeric(string):
    if string.isalnum():
        print(f'The string {string} is alphanumeric.')
    else:
        print(f'The string {string} is not alphanumeric.')
string='jasp123'     
alphanumeric(string)              

The string jasp123 is alphanumeric.


# Explanation: 

* Defining the function alphanumeric that takes one parameter string.
* Using the string.isalnum() inbuilt method to check whether the given string is alphanumeric. This method returns True if all characters in the string are letters or digits, and False otherwise.
* So directly using the If else statement, and check if its true, it will pring the string is alphanumeric. 
* Else it will print the string is not alphanumeric. Using the f-string method to pass the string into the print statement.
* Declaring the variable string and calling the function to check for reslts.

24. Extract all digits from a string.

In [19]:
def digit_extraction(string):    
    digits=''
    for i in string:
        if i.isdigit():  # This isdigit() method returns True if all the characters are digits, otherwise False. 
            digits+=i    # appending the i into digits variable
    return digits
string='Jasper123'
digit_extraction(string)

'123'

# Explanation: 

* Defining the function digit_extraction which takes one argument string.
* Delcaring a empty string variable named digits, used to store the extracted digits.
* Using the for loop and iterating the string passed into the function.
* using the isdigit() method to check if the iterated string is digit. This isdigit() method returns True if all the characters are digits, otherwise False. 
* So directly using the If statement with this method, if its true, appending the iterated string into the digits variable.
* Returning the digits variable.
* Declaring the string variable and finallly calling the function digit_extraction with string argument passed.


25. Extract all alphabets from a string.

In [22]:
def alpha_extraction(string):    
    letters=''
    for i in string:
        if i.isalpha():  # This isalpha() method returns True if all the characters are alphabet letters (a-z). 
            letters+=i    # appending the i into letters variable
    return letters
string='24Jasper123'
alpha_extraction(string)

'Jasper'

# Explanation: 

* Defining the function alpha_extraction which takes one argument string.
* Delcaring a empty string variable named letters, used to store the extracted letters.
* Using the for loop and iterating the string passed into the function.
* using the isalpha() method to check if the iterated string is letter. This isalpha() method returns True if all the characters are alphabet letters (a-z).
* So directly using the If statement with this method, if its true, appending the iterated string into the letters variable.
* Returning the letters variable.
* Declaring the string variable and finallly calling the function alpha_extraction with string argument passed.


26. Count the number of uppercase letters in a string.

In [31]:
def count_upper(string):    
    count=0
    for i in string:
        if i.isupper():  # This isupper() method returns True if all the characters are in upper case, otherwise False. 
            count+=1    # add 1 into count variable for each if statement which gets true
    return count
string='JaSPeR'
count_upper(string)

4

# Explanation: 

* Defining the function count_upper which takes one argument string.
* Delcaring a variable named count with value 0, used to count the upper case letters.
* Using the for loop and iterating the string passed into the function.
* using the isupper() method to check if the iterated string is in Upper case. This isupper() method returns True if all the characters are in upper case, otherwise False.
* So directly using the If statement with this method, if its true, adding 1 for every true statement into the variable count.
* Returning the count variable.
* Declaring the string variable and finallly calling the function count_upper with string argument passed.


27. Count the number of lowercase letters in a string.

In [34]:
def count_lower(string):    
    count=0
    for i in string:
        if i.islower():  # This islower() method returns True if all the characters are in lower case, otherwise False. 
            count+=1    # add 1 into count variable for each if statement which gets true
    return count
string='jaSpeR'
count_lower(string)

4

# Explanation: 

* Defining the function count_lower which takes one argument string.
* Delcaring a variable named count with value 0, used to count the lower case letters.
* Using the for loop and iterating the string passed into the function.
* using the islower() method to check if the iterated string is in lower case. This islower() method returns True if all the characters are in lower case, otherwise False.
* So directly using the If statement with this method, if its true, adding 1 for every true statement into the variable count.
* Returning the count variable.
* Declaring the string variable and finallly calling the function count_lower with string argument passed.


28. Swap the case of each character in a string.

In [36]:
def swapcase(string):    
    swaped_string=string.swapcase()
    return swaped_string
string='jaSpeR'
swapcase(string)

'JAsPEr'

# Explanation: 

* Defining the function swapcase which takes one argument string.
* Using the swapcase() method, this swapcase() method converts all uppercase characters to lowercase and vice versa of the given string and returns it. Storing this result in a variable swaped_string
* Returning the swaped_string variable.
* Declaring the string variable and finallly calling the function swapcase with string argument passed.


29. Remove a specific word from a string.

In [75]:
def remove_word(string, word):
    split= string.split()
    result=[]
    final=' '.join([char for char in split if char != word ])
    return final

string='Hello how is your day and'
word='and'
remove_word(string, word)

'Hello how is your day'

# Explanation:

1. Function Definition:
* def remove_word(string, word): defines a function named remove_word that takes two parameters: string (the input string) and word (the word to be removed).
2. Splitting the String:
* split = string.split() splits the input string into a list of words based on the default space delimiter. The result is stored in the split variable.
3. List Comprehension and Joining:
* [char for char in split if char != word] is a list comprehension that creates a new list containing words from the split list only if the word is not equal to the specified target word. ' '.join(...) then joins the filtered list of words into a string with spaces in between.
4. Returning the Result:
* return final returns the modified string without the specified word.
5. Example Usage:
* The code provides an example usage where the word 'and' is removed from the string 'Hello how is your day and'. The result is then printed.

30. Check if a string is a valid email address.

In [86]:
import re

email='rahu.jasper7@gmail.com'
pattern=r'[\w\.-]+@[\w\.-]+\.\w+$'

if re.match(pattern, email):
    print( 'This is a valid email address')
else:
    print( 'This is not a valid email address')



This is a valid email address


# Explanation:

* Impoting the re module ( regularization)
* Declaring the variable email and pattern, email contains the  email to get validated, pattern contains the regular expression pattern.
* The pattern uses the following components:
* ^: Anchors the pattern to the start of the string.
* [\w\.-]+: Matches one or more word characters (letters, digits, underscores) or dots or hyphens, which are valid characters in the username part of the email.
* @: Matches the "@" symbol.
* [\w\.-]+: Matches one or more word characters (letters, digits, underscores) or dots or hyphens, which are valid characters in the domain name part of the email.
* \.: Escapes and matches the literal dot (.) symbol.
* \w+$: Matches one or more word characters (letters, digits, underscores) at the end of the string (domain suffix, like ".com").
* Use re.match(pattern, email) to match the email against the pattern. If the match is successful, the email is considered valid and print the valid statement, else it will print the email is not valid.

31. Extract the username from an email address string.

In [88]:
def extract_username(email):
    username = email.split('@')[0]  # Split the email address at "@" and take the first part
    return username

email = "jasper@google.com"
result = extract_username(email)
print(result)

jasper


- Define a function named extract_username that takes an email parameter.
- Inside the function, split the email at the "@" symbol using the split() method. This will result in a list containing two parts: the username and the domain.
- Use indexing [0] to access the first part of the list, which is the username.
Return the username from the function.
- Declaring a variable contains an example email address.
- Call the extract_username function with the example email to see the return from function.

32. Extract the domain name from an email address string.

In [90]:
def extract_domain(email):
    domain = email.split('@')[1]  # Split the email address at "@" and take the second part
    return domain
email = "jasper@google.com"
extract_domain(email)

'google.com'

- Define a function named extract_domain that takes an email parameter.
- Inside the function, split the email at the "@" symbol using the split() method. This will result in a list containing two parts: the username and the domain.
- Use indexing [1] to access the first part of the list, which is the domain.
Return the domain from the function.
- Declaring a variable contains an example email address.
- Call the extract_domain function with the example email to see the return from function.

33. Replace multiple spaces in a string with a single space.

In [92]:
def replace_multiple_space(input_string):
    cleaned_string = ' '.join(input_string.split())  # Split the string at spaces and then join using a single space
    return cleaned_string

input_string = "Hello     world!   How   are   you?"
replace_multiple_space(input_string)

'Hello world! How are you?'

- Define a function named replace_multiple_space that takes an input_string parameter.
- Inside the function, use the split() method to split the input_string into a list of words. By default, split() splits the string on whitespace, treating consecutive spaces as a single delimiter.
- Use the join() method to join the list of words back into a string using a single space as the separator. This effectively replaces multiple spaces with a single space.
- Return the cleaned_string from the function.

34. Check if a string is a valid URL.

In [13]:
from urllib.parse import urlparse

def is_valid_url(url):
    try:
        result = urlparse(url)
        return all([result.scheme, result.netloc])
    except ValueError:
        return False

url_to_check = "https://twitter.com"

if is_valid_url(url_to_check):
    print(f"{url_to_check} is a valid URL.")
else:
    print(f"{url_to_check} is not a valid URL.")


https://twitter.com is a valid URL.


# Explanation:

- Import the urlparse function from the urllib.parse module. This function allows us to parse URLs and extract their components.
- Define a function named is_valid_url that takes a url parameter.
Inside the function, use a try block to handle possible exceptions during URL parsing.
- Use urlparse(url) to parse the given URL. The result is an object containing the URL's components like scheme, netloc, path, query, etc.
- Check if both the result.scheme (URL scheme, like "http", "https", etc.) and result.netloc (network location) are present. If both are present, it's considered a valid URL.
- If any exception occurs during parsing (indicating that the URL is not correctly formatted), the except ValueError block will catch it and return False.
- Call the is_valid_url function with the example URL to see whether each URL is considered valid or not.

35. Extract the protocol (http or https) from a URL string.

In [47]:
from urllib.parse import urlparse

def extract_protocol(url):
    try:
        result = urlparse(url)
        if result.scheme != '':
            return result.scheme
    except ValueError:
        return False
    
url_to_check = "https://example.com"

extract_protocol(url_to_check)
    

'https'

# Explanation:

- Import the urlparse function from the urllib.parse module. This function allows us to parse URLs and extract their components.
- Define a function named extract_protocol that takes a url parameter.
Inside the function, use a try block to handle possible exceptions during URL parsing.
- Use urlparse(url) to parse the given URL. The result is an object containing the URL's components like scheme, netloc, path, query, etc.
- Check if result.scheme (URL scheme, like "http", "https", etc.) present and if it is not empty i want it to return the result.scheme.
- If any exception occurs during parsing (indicating that the URL is not correctly formatted) the except ValueError block will catch it and return the print statement.
- Call the extract_protocol function with the example URL to find the protocol

36. Find the frequency of each character in a string.

In [69]:
import pandas as pd
def char_frequency(string):
    frequency = {}  # Create an empty dictionary to store character frequencies
    for char in string:
        if char in frequency:
            frequency[char] += 1  # Increment the frequency count if the character is already in the dictionary
        else:
            frequency[char] = 1   # Initialize the frequency count to 1 if the character is not in the dictionary
    return pd.DataFrame(frequency.items(), columns=['Characters', "Frequency"])
string = "Forever"

char_frequency(string)


Characters  Frequency
0          F          1
1          o          1
2          r          2
3          e          2
4          v          1

# Explanation: 

- Importing the pandas library to show the final result in a table format.
- We define a function char_frequency(string) that takes a string as input.
- Inside the function, we create an empty dictionary named frequency to store the frequency of each character.
- We iterate through each character in the string.
- For each character, we check if it is already present in the frequency dictionary using the in operator.
  - If the character is already in the dictionary, we increment its corresponding frequency count by 1.
  - If the character is not in the dictionary, we initialize its frequency count to 1.
- After iterating through all characters in the input string, we pass the items in frequency into the pandas DataFrame method to return it as in easy readable format.

37. Remove all punctuation from a string.

In [103]:
string =  "Hello, world! How is it going?"
result=''
for i in string:
    if i.isalnum():
        result+=i
    else:
        result+=" "
    
print(result)

Hello  world  How is it going 


# Explanation: 

* Declaring a variable string with a example string word.
* Declaring a variable with empty string value named result.
* Looping the string and iterates through i, using if statement, and the .isalnum() which used to check whether the specific string is alpha or numeric if its true, that specific letter will add into the result variable .
* Else if the letter is not alpha numeric eg, if its any puncutaction we are adding a empty space in the result variable.
* Printing the result variable

38. Check if a string contains only digits.

In [109]:
def str_digit(string):
    if string.isdigit():  # This isdigit() method returns True if all the characters are digits. 
        return f'{string} contains only digits'
    else:
        return f'{string} not contains only digits'
string='345123'
str_digit(string)

'345123 contains only digits'

# Explanation: 

* Defining the function str_digit which takes one argument string.
* using the  isdigit() method to check if string is numeric value. This isdigit() method returns True if all the characters are digits.
* So directly using the If statement with this method, if its true, returning the string contains digits using fstring, else returning the string and methioning not only digits.
* Declaring the string variable and finally calling the function str_digit with string argument passed.


39. Check if a string contains only alphabets.

In [116]:
def str_alpha(string):
    if string.isalpha():  # This isalpha() method returns True if all the characters are alphabets. 
        return f'{string} contains only alphabets'
    else:
        return f'{string} not contains only alphabets'
string='Jasper'
str_alpha(string)

'Jasper contains only alphabets'

# Explanation: 

* Defining the function str_alpha which takes one argument string.
* using the  isalpha() method to check if string contains only alphabets. This isdigit() method returns True if all the characters are alphabets.
* So directly using the If statement with this method, if its true, returning that the string contains only alphabets using fstring, else returning the string and mentioning not only alphabets.
* Declaring the string variable and finally calling the function str_alpha with string argument passed.


40. Convert a string to a list of characters.

In [1]:
input_string = "Hello, World!"
char_list = list(input_string)  # Converting the string to a list of characters
print(char_list)

['H', 'e', 'l', 'l', 'o', ',', ' ', 'W', 'o', 'r', 'l', 'd', '!']


# Explanation: 

* Declaring a variable with string value
* using the list() to convert the input string into list of characters and store it in the char_list variable
* Printing the char_list variable

41. Check if two strings are anagrams.

In [4]:
def are_anagrams(str1, str2):
    str1 = str1.replace(" ", "").lower()
    str2 = str2.replace(" ", "").lower() # Remove spaces and convert strings to lowercase for accurate comparison
    if sorted(str1) == sorted(str2):
        return f"{str1}' and '{str2}' are anagrams"
    else: 
        return f"{str1}' and '{str2}' are not anagrams"

str1='listen'
str2='silent'
are_anagrams(str1, str2)

"listen' and 'silent' are anagrams"

# Explanation:

1. Function Definition:
def are_anagrams(str1, str2): defines a function named are_anagrams that takes two strings (str1 and str2) as parameters.
2. Remove Spaces and Convert to Lowercase:
str1 = str1.replace(" ", "").lower(): Removes spaces and converts all characters in str1 to lowercase.
str2 = str2.replace(" ", "").lower(): Similarly, removes spaces and converts all characters in str2 to lowercase.
This step ensures that spaces and case differences do not affect the anagram comparison.
3. Check for Anagrams:
if sorted(str1) == sorted(str2):: Checks if the sorted list of characters in str1 is equal to the sorted list of characters in str2.
If the sorted character lists are the same, it means that the two strings are anagrams.
4. Return Result:
return f"{str1}' and '{str2}' are anagrams": If the strings are anagrams, return a message indicating that they are anagrams.
else: return f"{str1}' and '{str2}' are not anagrams": If the strings are not anagrams, return a message indicating that they are not.
* Example Usage:
str1 = 'listen' and str2 = 'silent' are example strings provided.
The are_anagrams function is then called with these example strings.

42. Encode a string using a Caesar cipher.

In [59]:
string= 'Hello I will call you by tomorrow 12pm'
shift= 2
def ceasar_cipher(string, shift):
    string=string.lower()
    result =''
    for i in string:
        if i.isalpha():
            ceasar_code= chr((ord(i)+shift-ord('a'))% 26 + ord('a'))
            result+=ceasar_code
        else:
            result+=i
    return result
ceasar_cipher(string, shift)

'jgnnq k yknn ecnn aqw da vqoqttqy 12ro'

Explanation:

1. Input Variables:
string = 'hello i will call you by tomorrow 12pm': The original string that you want to encrypt using the Caesar cipher.
shift = 2: The shift value for the Caesar cipher. Each letter in the original string will be shifted by this amount.
2. Function Definition:
def ceasar_cipher(string, shift):: Defines a function named ceasar_cipher that takes two parameters - string (the input string to be encrypted) and shift (the shift value for the Caesar cipher). converting all the string into lower method using lower.
3. Result Initialization:
result = '': Initializes an empty string (result) where the encrypted characters will be stored.
4. Iteration through Each Character:
for i in string:: Iterates through each character in the input string.
5. Check if Character is an Alphabetical Letter:
if i.isalpha():: Checks if the current character i is an alphabetical letter. else: If the character is not an alphabetical letter, it is appended to the result without modification.
6. Caesar Cipher Encryption:
ceasar_code = chr((ord(i) + shift - ord('a')) % 26 + ord('a')): Calculates the Caesar cipher code for the current letter:
ord(i): Gets the ASCII code of the current letter.
(ord(i) + shift - ord('a')): Calculates the new position of the letter after the shift.
% 26: Handles wrapping around the alphabet (assuming a 26-letter alphabet).
+ ord('a'): Adjusts the result to the ASCII code of the letter 'a'.
chr(...): Converts the final ASCII code back to a character.
result += ceasar_code: Appends the encrypted letter to the result string.
7. Return Result:
return result: Returns the final encrypted string.
* Example Usage:
ceasar_cipher(string, shift): Calls the ceasar_cipher function with the provided string and shift value.

43. Decode a Caesar cipher encoded string.

In [61]:
string= 'jgnnq K yknn ecnn aqw da vqoqttqy 12ro'
shift= 2
def ceasar_cipher_decode(string, shift):
    string=string.lower()
    result =''
    for i in string:
        if i.isalpha():
            ceasar_code= chr((ord(i)-shift-ord('a'))% 26 + ord('a'))
            result+=ceasar_code
        else:
            result+=i
    return result
ceasar_cipher_decode(string, shift)

'hello i will call you by tomorrow 12pm'

Explanation:

1. Input Variables:
string = 'jgnnq k yknn ecnn aqw da vqoqttqy 12ro': The original string that you want to encrypt using the Caesar cipher.
shift = 2: The shift value for the Caesar cipher. Each letter in the original string will be shifted by this amount.
2. Function Definition:
def ceasar_cipher(string, shift):: Defines a function named ceasar_cipher that takes two parameters - string (the input string to be encrypted) and shift (the shift value for the Caesar cipher). Converting all the string into lower method using lower.
3. Result Initialization:
result = '': Initializes an empty string (result) where the encrypted characters will be stored.
4. Iteration through Each Character:
for i in string:: Iterates through each character in the input string.
5. Check if Character is an Alphabetical Letter:
if i.isalpha():: Checks if the current character i is an alphabetical letter. else: If the character is not an alphabetical letter, it is appended to the result without modification.
6. Caesar Cipher Encryption:
ceasar_code = chr((ord(i) - shift - ord('a')) % 26 + ord('a')): Calculates the Caesar cipher code for the current letter:
ord(i): Gets the ASCII code of the current letter.
(ord(i) + shift - ord('a')): Calculates the new position of the letter after the shift.
% 26: Handles wrapping around the alphabet (assuming a 26-letter alphabet).
+ ord('a'): Adjusts the result to the ASCII code of the letter 'a'.
chr(...): Converts the final ASCII code back to a character.
result += ceasar_code: Appends the encrypted letter to the result string.
7. Return Result:
return result: Returns the final encrypted string.
* Example Usage:
ceasar_cipher(string, shift): Calls the ceasar_cipher function with the provided string and shift value.

44. Find the most frequent word in a string.

In [139]:
import re
def most_frequent(string):
    clean_string = re.sub(r'[^\w\s]', '', string).lower()
    split= clean_string.split()
    frequent= {}
    for i in split:
        if i in frequent:
            frequent[i]+=1
        else:
            frequent[i] =1
    most_frequent = max(frequent, key=frequent.get)
    frequency = frequent[most_frequent]
    return f"The most frequent word is '{most_frequent}' and repeated {frequency} times."
string= 'Hello! how are you, how is your how, day?'
most_frequent(string)

"The most frequent word is 'how' and repeated 3 times."

Explanation:

1. Import re Module:
import re: Imports the regular expression module for text processing.
2. Function Definition:
def most_frequent(string):: Defines a function named most_frequent that takes a string as input.
3. Text Cleaning:
clean_string = re.sub(r'[^\w\s]', '', string).lower(): Removes non-word and non-whitespace characters using re.sub(). The result is then converted to lowercase using .lower().
4. Split the Cleaned String:
split = clean_string.split(): Splits the cleaned string into a list of words using split().
5. Count Word Frequencies:
frequent = {}: Initializes an empty dictionary to store word frequencies.
for i in split:: Iterates through the list of words.
If the word is already in the dictionary, its frequency is incremented.
If the word is not in the dictionary, a new entry is created with a frequency of 1.
6. Find Most Frequent Word:
most_frequent = max(frequent, key=frequent.get): Finds the key (word) with the maximum value (frequency) in the dictionary.
frequency = frequent[most_frequent]: Retrieves the frequency of the most frequent word.
7. Return Result:
return f"The most frequent word is '{most_frequent}' and repeated {frequency} times.": Returns a formatted string indicating the most frequent word and its frequency.
* Example Usage:
string = 'Hello! how are you, how is your how, day?': An example string is provided.
most_frequent(string): The function is called with the example string.

45. Find all unique words in a string.

In [2]:
import re

def unique_words(string):
    clean_string = re.sub(r'[^\w\s]', '', string).lower() # Remove punctuation and convert to lowercase
    words = set(clean_string.split())  # Split the string into words and convert to a set for uniqueness
    return "Unique words:", words

string = "Hello world, hello there! How's the world?"
unique_words(string)

('Unique words:', {'hello', 'hows', 'the', 'there', 'world'})

Explanation:

* Import re Module:
import re: Imports the regular expression module for text processing.
* Function Definition:
def unique_words(string):: Defines a function named unique_words that takes a string as input.
* Text Cleaning:
clean_string = re.sub(r'[^\w\s]', '', string).lower(): Removes non-word and non-whitespace characters using re.sub(). The result is then converted to lowercase using .lower().
* Split the Cleaned String into Words:
words = set(clean_string.split()): Splits the cleaned string into words using split() and then converts the list of words into a set.
Using a set ensures that only unique words are retained, as sets do not allow duplicate elements.
* Return Result:
return "Unique words:", words: Returns a tuple containing a label ("Unique words:") and the set of unique words.
* Example Usage:
string = "Hello world, hello there! How's the world?": An example string is provided.
unique_words(string): The function is called with the example string.

46. Count the number of syllables in a string.

In [8]:
import re

def count_syllables(word):
    
    vowel_groups = re.findall(r'[aeiouy]+', word, re.IGNORECASE) # Count vowel groups using regular expression
    return f"No of Syllables present in '{word}' is {len(vowel_groups)}"

word= 'Hello world 43'
count_syllables(word)

"No of Syllables present in 'Hello world 43' is 3"

Explanation:

* Import re Module:
import re: Imports the regular expression module for text processing.
* Function Definition:
def count_syllables(word):: Defines a function named count_syllables that takes a word as input.
* Count Vowel Groups:
vowel_groups = re.findall(r'[aeiouy]+', word, re.IGNORECASE): Uses re.findall() to find all occurrences of sequences of vowels or vowel-like sounds in the word. The regular expression [aeiouy]+ matches one or more consecutive vowels (case-insensitive).
re.IGNORECASE: This flag makes the pattern matching case-insensitive, allowing it to match both uppercase and lowercase vowels.
* Return Result:
return f"No of Syllables present in '{word}' is {len(vowel_groups)}": Returns a formatted string indicating the number of syllables found in the word. The length of the vowel_groups list gives the count of syllables.
* Example Usage:
word = 'Hello world 43': An example word is provided. Note that the function may not accurately handle numbers, as it is primarily designed for words.
count_syllables(word): The function is called with the example word.

47. Check if a string contains any special characters.

In [9]:
def spl_characters(string):
    if string.isalnum() == 0:
        return f"'{string}' contains special Characters."
    else:
        return f"'{string}' does not contains special Characters."
string = 'Hello3#%'            
print(spl_characters(string))

'Hello3#%' contains special Characters.


Explanation:

* Function Definition:
def spl_characters(string):: Defines a function named spl_characters that takes a string as input.
* Check for Special Characters:
if string.isalnum() == 0:: Checks if the string contains alphanumeric characters only. The method isalnum() returns True if all characters in the string are alphanumeric (letters or numbers), and False otherwise.
return f"'{string}' contains special characters.": If the string does not contain only alphanumeric characters (i.e., if isalnum() returns False), this branch is executed, and a message is returned indicating that the string contains special characters.
* No Special Characters Case:
else:: If the string contains only alphanumeric characters (i.e., if isalnum() returns True), this branch is executed.
return f"'{string}' does not contain special characters.": In this case, a message is returned indicating that the string does not contain special characters.
* Example Usage:
string = 'Hello3#%': An example string is provided with a mix of alphanumeric and special characters.
print(spl_characters(string)): The function is called with the example string, and the result is printed.

48. Remove the nth word from a string.

In [140]:
def remove_string(string, n):
    split= string.split()  # Split into words
    if 0 <= n <= len(split)-1: # Check if n is within the valid range (0 <= n <= len(split)-1)
        removed= split.pop(n) # using pop method 
        final_word= ' '.join(split)  # using the join method to join the remaining words
        return f'''original word: {string}
Modified word : {final_word}
Removed word :  {removed}
        '''
    else:
        return 'Try within the range of index'
string= 'Hello Arjun How are you'
print(remove_string(string  , 3))

original word: Hello Arjun How are you
Modified word : Hello Arjun How you
Removed word :  are
        


Explanation:

* Function Definition:
def remove_string(string, n):: Defines a function named remove_string that takes a string (string) and an index (n) as input.
* Split the String:
split = string.split(): Splits the input string into a list of words using the split() method.
* Check for Valid Index:
if 0 <= n <= len(split)-1:: Checks if the index n is within the valid range (0 to the length of the split words - 1).
* Remove Word at Specified Index:
removed = split.pop(n): Uses the pop() method to remove the word at the specified index (n) from the list split. The removed word is stored in the variable 
* Join Remaining Words:
final_word = ' '.join(split): Uses the join() method to join the remaining words in the list split into a single string. This represents the modified word.
* Return Formatted String:
The function returns a formatted string using an f-string that includes the original word, modified word, and removed word.
* Invalid Index Case:
else:: If the index is not within the valid range, the function returns a message indicating that the user should try within the valid index range.
* Example Usage:
string = 'Hello Arjun How are you': An example string is provided.
print(remove_string(string, 1)): The function is called with the example string and index.


49. Insert a word at the nth position in a string.

In [146]:
def insert_word(string, n, word):
    split= string.split()  # Split into words
    if 0 <= n <= len(split):  #setting the condition n should be greater than or equal 0 and lesser or equals to length of words splitted
        split.insert(n , word )
        final_word= ' '.join(split)  # using the join method to join the remaining words
    else:
        return 'Try within the range of index'
    return f'''original word: {string}
Modified word : {final_word}
Added word :  {word}
        '''
string= 'Hello Arjun How are you'
print(insert_word(string  , 2, 'bhai'))

original word: Hello Arjun How are you
Modified word : Hello Arjun bhai How are you
Added word :  bhai
        


Explanation:

* Function Definition:
def insert_word(string, n, word):: Defines a function named insert_word that takes a string (string), an index (n), and a word (word) as input.
* Split the String:
split = string.split(): Splits the input string into a list of words using the split() method.
* Check for Valid Range:
if 0 <= n <= len(split):: Checks if the index n is within the valid range (0 to the length of the split words).
* Insert the Word and Join:
split.insert(n, word): Inserts the word at the specified index (n) in the list split.
final_word = ' '.join(split): Joins the remaining words to form a modified string.
* Return Result or Error Message:
Returns the formatted string with the original, modified, and added words if n is within a valid range.
Returns an error message if n is not within a valid range.
* Example Usage:
string = 'Hello Arjun How are you': An example string is provided.
print(insert_word(string, 2, 'bhai')): The function is called with the example string, index (2), and the word to insert ('bhai').

50. Convert a CSV string to a list of lists.

In [2]:
def csv_str(csv_string):
    split= csv_string.split('\n')
    result=[]
    for i in split:
        list_=i.split(',')
        result.append(list_)
    return result

csv_string = "Product, Price, Quantity\nApple, 1.00, 10\nBanana, 0.75, 15\nOrange, 1.25, 8"
list_=csv_str(csv_string)
for row in list_:
    print( row )

['Product', ' Price', ' Quantity']
['Apple', ' 1.00', ' 10']
['Banana', ' 0.75', ' 15']
['Orange', ' 1.25', ' 8']


Explanation:

1. Function Definition: The `csv_str` function is declared to take a CSV string as input.
2. Splitting Lines: The CSV string is split into a list of strings using the newline character (`'\n'`), resulting in a list where each element represents a line in the CSV.
3. Result List Initialization: An empty list named `result` is initialized to store the final result.
4. Processing Each Line:A loop iterates over each line in the CSV, represented by the variable `i`.
5. Splitting Values: Each line (`i`) is split into a list of values using the comma (`,`) as the separator, and the resulting list is assigned to `list_`.
6. Appending to Result List: The list of values (`list_`) for each line is appended to the `result` list. Now, `result` is a list of lists, where each inner list represents a row of values from the CSV.
7. Returning Result: The function returns the final result, which is a list of lists representing the CSV data.
8. CSV String Definition: A CSV string containing product information is defined, with columns for Product, Price, and Quantity.
9. Function Call: The `csv_str` function is called with the provided CSV string, and the result is stored in the variable `list_`.
10. Printing Result: A loop iterates through each row in the `list_`, and each row is printed, displaying the parsed information from the CSV.

# List Based Practice Problem 

1. Create a list with integers from 1 to 10.

In [9]:
list_=[i for i in range(1,11)]
print(list_)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


- We use a list comprehension, a concise way to create lists in Python, to generate the list of integers from 1 to 10.
- The expression [i for i in range(1, 11)] iterates over the range of numbers from 1 (inclusive) to 11 (exclusive), and for each number i, it adds i to the list.
- The resulting list is stored in the variable list_.
- We print the list_ using the print() statement.

2. Find the length of a list without using the `len()` function.

In [13]:
def length_list(list_):
    length=0
    for i in list_:
        length+=1
    return f"The length of the list is {length}"

list_=[1,2,3,4,5,6,7,8,9,10]
length_list(list_)

'The length of the list is 10'

# Explanation : 

* Function Definition:
Defines a function named length_list that takes a single argument list_.
* Length Variable Initialization:
Initializes a variable length to 0. This variable will be used to count the length of the list.
* Loop through List:
Initiates a loop that iterates through each element (i) in the input list list_.
* Incrementing Length:
Increments the length variable by 1 for each element in the list, effectively counting the number of elements in the list.
* Returning Result:
Returns a formatted string stating the length of the list.

3. Append an element to the end of a list.

In [22]:
names=['Arjun', 'vijay','Prakash']
names.append('Leo')  # using the append method to add new element to the list in default it append to end
print(names)


['Arjun', 'vijay', 'Prakash', 'Leo']


# Explanation :

* Initialize a example list of names and declared the variable names
* used the append() method to add a new element to the list at the end.
* used print () function to print the list.

4. Insert an element at a specific index in a list.

In [12]:
def _insert_element(string, index,insert_word):  # Creating a function with 3 parameters
    string.insert(index, insert_word) # using insert method with takes index and value parameter
    return string
string=['Arjun', 'vijay','Prakash']
insert_word= 'Leo'
index=0
_insert_element(string, index,insert_word)

['Leo', 'Arjun', 'vijay', 'Prakash']

Explanation:

* Function Definition:
Defines a function named _insert_element with three parameters: string (a list), index (the position to insert), and insert_word (the element to insert).
* Insertion Operation:
Uses the insert method on the provided list (string) to insert the specified insert_word at the given index.
* Return Statement:
Returns the modified list (string) after the insertion.
* Usage:
Defines a list named string containing names.
Specifies the insert_word as 'Leo' and the index as 0.
Calls the _insert_element function with these values and stores the result in the variable result.

5. Remove an element from a list by its value.

In [15]:
string=['Arjun','Leo', 'vijay','Prakash']
remove_value= 'Leo'
string.remove(remove_value) # using remove() method to remove a specific element, which takes the removal value
print(string)



['Arjun', 'vijay', 'Prakash']


Explanation:

* List Definition:
Initializes a list named string with elements 'Arjun', 'Leo', 'vijay', and 'Prakash'.
* Remove Operation:
Specifies the value to be removed as 'Leo' and uses the remove() method on the list string.
The remove() method removes the first occurrence of the specified value from the list.
* Printing Result:
Prints the modified list after removing 'Leo'.

6. Remove an element from a list by its index.

In [25]:
string=['Arjun','Leo', 'vijay','Prakash']
removed=string.pop(2) # using pop() method to remove an element at specific index
print(f'''Updated element = {string}
removed element = {removed}
''')

Updated element = ['Arjun', 'Leo', 'Prakash']
removed element = vijay



Explanation:

* List Definition:
Initializes a list named string with elements 'Arjun', 'Leo', 'vijay', and 'Prakash'.
* Pop Operation:
Uses the pop() method on the list string with index 2.
The pop() method removes the element at the specified index (2 in this case) and returns the removed element. In this example, the element 'vijay' at index 2 is removed, and the removed element is stored in the variable removed.
* Printing Result:
Prints the updated list (string) after the removal and the removed element.

7. Check if an element exists in a list.

In [27]:
def _check_element(string, search_element):
    if search_element in string:
        return f'{search_element} present in the string.'
    else: 
        return f'{search_element} not present.'
string=['Arjun','Leo', 'vijay','Prakash']
search_element='Leo'
_check_element(string, search_element)

'Leo present in the string.'

Explanation:

* Function Definition:
Defines a function named _check_element with two parameters - string (a list) and search_element (the element to search for).
* Element Check:
Uses an if statement to check if the search_element is present in the list string using the in operator.
* Return Statement (Element Found):
If the search_element is found, returns a formatted string indicating that the element is present in the string.
* Return Statement (Element Not Found):
If the search_element is not found, returns a formatted string indicating that the element is not present in the string.
* Usage:
Defines a list named string containing names.
Specifies the search_element as 'Leo'.
Calls the _check_element function with these values and stores the result in the variable result.

8. Find the index of the first occurrence of an element in a list.

In [32]:
string=['Arjun','Leo', 'Arjun','vijay','Prakash']
element='Arjun'
index_=string.index(element)
print(f' The index of the first occurance of {element} is index {index_}')

 The index of the first occurance of Arjun is index 0


Explanation:

* List Definition:
Initializes a list named string with elements 'Arjun', 'Leo', 'Arjun', 'vijay', and 'Prakash'.
* Indexing Operation:
Uses the index() method on the list string to find the index of the first occurrence of the specified element ('Arjun' in this case).
* Printing Result:
Prints a formatted string indicating the index of the first occurrence of the specified element.

9. Count the occurrences of an element in a list.

In [37]:
string=['Arjun','Leo', 'Arjun','vijay','Prakash']
element='Arjun'
count=string.count(element)
print(f' The element {element} occurs {count} times')

 The element Arjun occurs 2 times


Explanation:

* List Definition:
Initializes a list named string with elements 'Arjun', 'Leo', 'Arjun', 'vijay', and 'Prakash'.
* Count Operation:
Uses the count() method on the list string to count the number of occurrences of the specified element ('Arjun' in this case).
* Printing Result:
Prints a formatted string indicating the number of occurrences of the specified element.

10. Reverse the order of elements in a list.

In [41]:
string=['Arjun','Leo', 'Arjun','vijay','Prakash']
reverse_string= string.reverse()  #using reverse method
print(f'''Original string = {string}
reverse string = {reverse_string}''')

Original string = ['Prakash', 'vijay', 'Arjun', 'Leo', 'Arjun']
reverse string = None


Explanation:

* List Definition:
Initializes a list named string with elements 'Arjun', 'Leo', 'Arjun', 'vijay', and 'Prakash'.
* Reversal Operation:
Uses the reverse() method on the list string. The reverse() method reverses the elements of the list in-place.
* Printing Result:
Prints a formatted string indicating the original list string and the result of the reverse() method.


11. Sort a list in ascending order.

In [48]:
string=['Arjun','Leo', 'Arjun','vijay','Prakash']
string.sort()
print(f'Sorted string = {string}')

Sorted string = ['Arjun', 'Arjun', 'Leo', 'Prakash', 'vijay']


Explanation:

* List Definition:
Initializes a list named string with elements 'Arjun', 'Leo', 'Arjun', 'vijay', and 'Prakash'.
* Sorting Operation:
Uses the sort() method on the list string. The sort() method sorts the elements of the list in-place default ascending order.
* Printing Result:
Prints a formatted string indicating the sorted list string.

12. Sort a list in descending order.

In [50]:
string=['Arjun','Leo', 'Arjun','vijay','Prakash']
string.sort(reverse=True)
print(f'Sorted string = {string}')

Sorted string = ['vijay', 'Prakash', 'Leo', 'Arjun', 'Arjun']


Explanation:

* List Definition:
Initializes a list named string with elements 'Arjun', 'Leo', 'Arjun', 'vijay', and 'Prakash'.
* Sorting Operation (Descending Order):
Uses the sort() method on the list string with the argument reverse=True.
The sort() method sorts the elements of the list in-place in descending order.
* Printing Result:
Prints a formatted string indicating the sorted list string in descending order.

13. Create a list of even numbers from 1 to 20.

In [2]:
def even(n):
    even_number=[]
    for i in range(1,n+1):
        if i %2==0:
            even_number.append(i)
        else:
            pass
    return f'List of Even Numbers from 1-{n} :{even_number}'
n=20
even(n)

'List of Even Numbers from 1-20 :[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]'

Explanation:

* Function Definition:
Defines a function named 'even' that takes a single parameter 'n'.
* Even Numbers List Initialization:
Initializes an empty list named 'even_number' to store even numbers.
* Loop through Numbers:
Initiates a loop that iterates through numbers from 1 to 'n'.
* Checking and Appending:
Checks if the current number 'i' is even. If so, appends it to the 'even_number' list.
* Return Statement:
Returns a formatted string indicating the list of even numbers from 1 to 'n'.
* Usage:
Calls the 'even' function with the value 'n' as an argument and stores the result in the variable 'even_numbers_list'.

14. Create a list of odd numbers from 1 to 20.

In [5]:
def odd_(n):
    odd_number=[]
    for i in range(1,n+1):
        if i %2!=0:
            odd_number.append(i)
        else:
            pass
    return f'List of Odd Numbers from 1-{n} :{odd_number}'
n=20
odd_(n)

'List of Odd Numbers from 1-20 :[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]'

Explanation:

* Function Definition:
Defines a function named 'odd_' that takes a single parameter 'n'.
* Odd Numbers List Initialization:
Initializes an empty list named 'odd_number' to store odd numbers.
* Loop through Numbers:
Initiates a loop that iterates through numbers from 1 to 'n'.
* Checking and Appending:
Checks if the current number 'i' is odd. If so, appends it to the 'odd_number' list.
* Return Statement:
Returns a formatted string indicating the list of odd numbers from 1 to 'n'.
* Usage:
Calls the 'odd_' function with the value 'n' as an argument and stores the result in the variable 'result'.

15. Find the sum of all elements in a list.

In [9]:
list_=[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
total=sum(list_)
print(f'Total = {total}')

Total = 110


Explanation:

* List Definition:
Initializes a list named list_ containing the numbers 2, 4, 6, 8, 10, 12, 14, 16, 18, 20.
* Sum Calculation:
Uses the sum() function to calculate the sum of all elements in the list list_.
The sum() function adds up all the numbers in the iterable (in this case, the elements of the list).
* Printing Result:
Prints a formatted string indicating the total sum of the elements in the list list_.

16. Find the maximum value in a list.

In [11]:
list_=[2, 4, 6, 50, 10, 12, 14, 16, 18, 20]
maximum=max(list_)
print(f'Maximum number is {maximum}')

Maximum number is 50


Explanation:

* List Definition:
Initializes a list named list_ containing the numbers 2, 4, 6, 50, 10, 12, 14, 16, 18, 20.
* Maximum Calculation:
Uses the max() function to find the maximum value in the list list_.
The max() function returns the maximum value from the iterable (in this case, the elements of the list).
* Printing Result:
Prints a formatted string indicating the maximum value in the list list_.

17. Find the minimum value in a list.

In [13]:
list_=[2, 4, 6, 50, 10, 12, 14, 16, 18, 20]
minimum=min(list_)
print(f'Minimum number is {minimum}')

Minimum number is 2


Explanation:

* List Definition:
Initializes a list named list_ containing the numbers 2, 4, 6, 50, 10, 12, 14, 16, 18, 20.
* Minimum Calculation:
Uses the min() function to find the minimum value in the list list_.
The min() function returns the minimum value from the iterable (in this case, the elements of the list).
* Printing Result:
Prints a formatted string indicating the minimum value in the list list_.

18. Create a list of squares of numbers from 1 to 10.

In [20]:
def squares(n):
    squares=[]
    for i in range(1,n+1):
        squares.append(i*i)
    return f'List of squares of Numbers from 1-{n} :{squares}'
n=10
squares(n)

'List of squares of Numbers from 1-10 :[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]'

Explanation:

* Function Definition:
Defines a function named 'squares' that takes a single parameter 'n'.
* Squares List Initialization:
Initializes an empty list named 'squares' to store the squares of numbers.
* Loop through Numbers:
Initiates a loop that iterates through numbers from 1 to 'n'.
* Calculating Squares:
Appends the square of the current number 'i' to the 'squares' list.
* Return Statement:
Returns a formatted string indicating the list of squares of numbers from 1 to 'n'.
* Usage:
Calls the 'squares' function with the value 'n' as an argument and stores the result in the variable 'result'.






19. Create a list of random numbers.

In [27]:
import random

   
random_numbers=[ random.randint(1,100) for i in range(10)]
print(random_numbers)

[25, 2, 83, 59, 56, 10, 85, 62, 10, 32]


Explanation:

* Importing the 'random' Module:
The import random statement imports the 'random' module, which provides functions for generating random numbers.
* List Comprehension for Random Numbers:
The line random_numbers = [random.randint(1, 100) for i in range(10)] uses a list comprehension to generate a list of 10 random integers.
random.randint(1, 100) generates a random integer between 1 (inclusive) and 100 (inclusive).
The list comprehension [... for i in range(10)] repeats this process 10 times to create a list of 10 random numbers.
* Printing Result:
The print(random_numbers) statement prints the list of 10 random numbers generated using the 'random' module.
The output will be a list of 10 random integers between 1 and 100.





20. Remove duplicates from a list.

In [28]:
my_list = [10, 20, 30, 20, 40, 10, 50, 30]
unique_list = list(set(my_list))
print("List without duplicates:", unique_list)

List without duplicates: [40, 10, 50, 20, 30]


Explanation:

* List Definition:
Initializes a list named my_list containing some elements with duplicates.
* Removing Duplicates using a Set:
Uses the set() function to create a set from my_list. A set automatically removes duplicate elements, leaving only unique elements.
* Converting Set back to List:
Converts the set obtained in the previous step back to a list using the list() constructor.
This step is necessary because sets don't maintain the order of elements.
* Printing Result:
Prints a formatted string indicating the list without duplicates.

21. Find the common elements between two lists.

In [5]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

common_elements = [value for value in list1 if value in list2]

print("Common elements:", common_elements)

Common elements: [3, 4, 5]


Explanation:

* List Initialization:
Initializing two lists list1 and list2 with values.

* List Comprehension for Common Elements:
common_elements variable is created using a list comprehension.It iterates through each value in list1.
Adds the value to common_elements only if it is also present in list2.
* Print Statement:
Prints the common elements found.

22. Find the difference between two lists.

In [4]:
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

diff_elements = [value for value in list1 if value  not in list2]
diff_elements2=[value for value in list2 if value  not in list1]
print("Different elements presented in list 1:", diff_elements)
print("Different elements presented in list 2:", diff_elements2)

Different elements presented in list 1: [1, 2]
Different elements presented in list 2: [6, 7]


Explanation:

* List Initialization:
list1 is set to [1, 2, 3, 4, 5].
list2 is set to [3, 4, 5, 6, 7].
* List Comprehension for Different Elements (List 1):
diff_elements is created using a list comprehension.
It iterates through each element in list1.
Includes the element in diff_elements only if it is not present in list2.
* List Comprehension for Different Elements (List 2):
diff_elements2 is created using a list comprehension.
It iterates through each element in list2.
Includes the element in diff_elements2 only if it is not present in list1.
* Print Statements:
Prints the different elements found in each list.

23. Merge two lists.

In [16]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

list1.extend(list2)

print("Merged List:", list1)

Merged List: [1, 2, 3, 4, 5, 6]


Explanation:
    
* List Initialization:
list1 is initialized with elements [1, 2, 3].
list2 is initialized with elements [4, 5, 6].
* Using extend() Method to Merge Lists:
The extend() method is called on list1 with list2 as an argument.
This method modifies list1 in place by adding all elements from list2 to the end of list1.
* Print Statement:
Prints the result after merging.

24. Multiply all elements in a list by 2.

In [20]:
list_= [1, 2, 3]
multiply_= [i*2 for i in list_ ]
print("Multiplied list:", multiply_)

Multiplied list: [2, 4, 6]


Explanation: 
    
* List Initialization:
list_ is initialized with elements [1, 2, 3].
* List Comprehension to Multiply Elements by 2:
A list comprehension is used to create a new list named multiply_.
It iterates through each element i in list_.
Multiplies each element by 2 (i * 2) and adds the result to the new list.
* Print Statement:
Prints the result after multiplication.

25. Filter out all even numbers from a list.

In [26]:
list_=[1,2,3,4,12,6,7,8,10, 15]
even_number=[i for i in list_ if i%2==0]
print("even numbers:",even_number)

even numbers: [2, 4, 12, 6, 8, 10]


Explanation: 
    
* List Initialization:
list_ is initialized with elements [1, 2, 3, 4, 12, 6, 7, 8, 10, 15].
* List Comprehension to Extract Even Numbers:
A list comprehension is used to create a new list named even_number.
It iterates through each element i in list_.
Includes the element in even_number only if it is an even number (i % 2 == 0).
* Result:
The list even_number now contains only the even numbers from the original list.
* Print Statement:
Prints the list of even numbers.

26. Convert a list of strings to a list of integers.

In [33]:
string_list = ["10", "20", "30", "40", "50"]
int_list= [int(i) for i in string_list]
print(f'''String List: {string_list}
Converted list of integers : {int_list}''')

String List: ['10', '20', '30', '40', '50']
Converted list of integers : [10, 20, 30, 40, 50]


Explanation: 
    
* List Initialization:
string_list is initialized with string elements ["10", "20", "30", "40", "50"].
* List Comprehension to Convert Strings to Integers:
A list comprehension is used to create a new list named int_list.
It iterates through each string element i in string_list.
Converts each string element to an integer using int(i) and adds the result to the new list.
* Print Statement:
Prints the original string list and the new list of integers.

27. Convert a list of integers to a list of strings.

In [34]:
int_list =[10, 20, 30, 40, 50]
str_list= [str(i) for i in string_list]
print(f'''Integer List: {int_list}
Converted list of String : {str_list}''')

Integer List: [10, 20, 30, 40, 50]
Converted list of String : ['10', '20', '30', '40', '50']


Explanation: 
    
* List Initialization:
int_list is initialized with string elements [10, 20, 30, 40, 50].
* List Comprehension to Convert integers to strings:
A list comprehension is used to create a new list named str_list.
It iterates through each integer element i in int_list.
Converts each int element to an strings using str(i) and adds the result to the new list.
* Print Statement:
Prints the original int list and the new list of strings.

28. Flatten a nested list.

In [15]:
nested_list = [[1, 2, 3],[4, 5], [6, 7, 8, 9],10]
flatened_lst=[]
for i in nested_list:
    if isinstance(i, list):
        flatened_lst.extend(i)
    else:
        flatened_lst.append(i)
        
print('Flattend List: ',flatened_lst)

Flattend List:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Explanation:
    
* List Initialization:
nested_list is initialized with elements, including sublists and a non-list element (10).
* Iterating through the Nested List:
The for loop iterates through each item in nested_list.
* Checking if the Item is a List:
isinstance(item, list) checks whether the current item is a list.
* Handling Lists and Non-List Elements:
If the item is a list, it extends the flatened_lst with its elements.
If the item is not a list, it appends the item directly to flatened_lst.
* Print Statement:
Prints the flattened list.

29. Create a list of the first 10 Fibonacci numbers.

In [12]:
def fibonacci(n):
    fibonacci_numbers=[0,1]
    for i in range(2,n):
        value= fibonacci_numbers[-1]+fibonacci_numbers[-2]
        fibonacci_numbers.append(value)

    return f'The list of first {n} Fibonacci numbers: {fibonacci_numbers}'

n= 10
result= fibonacci(n)
print(result)

The list of first 10 Fibonacci numbers: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


Explanation: 

* Function Definition:
The fibonacci function takes an argument n, which represents the number of Fibonacci numbers to generate.
* Fibonacci Numbers Initialization:
fibonacci_numbers is initialized with the first two Fibonacci numbers [0, 1].
* Loop to Generate Fibonacci Numbers:
The for loop iterates from 2 to n-1 to generate additional Fibonacci numbers.
Each new Fibonacci number is the sum of the last two numbers in the list.
* Return Statement:
The function returns a formatted string containing the list of the first n Fibonacci numbers.
* Function Call:
The function is called with n = 10, generating the first 10 Fibonacci numbers.
* Print Statement:
Prints the result, which is a formatted string showing the list of the first 10 Fibonacci numbers.

30. Check if a list is sorted.

In [ ]:
def is_sorted(lst):
    return all(lst[i] <= lst[i + 1] for i in range(len(lst) - 1))

lst=  [10, 20, 30, 40, 50]
result= is_sorted(lst)
print(f'The give list is sorted in ascending order: {result}')

Explanation: 
    
* Function Definition:
def is_sorted(lst): defines a function named is_sorted that takes a list lst as its parameter.
* Generator Expression:
lst[i] <= lst[i + 1] for i in range(len(lst) - 1) is a generator expression.
It iterates over the indices (i) from 0 to len(lst) - 2.
For each index, it checks if the element at the current index (lst[i]) is less than or equal to the element at the next index (lst[i + 1]).
* all() Function:
all(...) takes the values produced by the generator expression.
It returns True if all values are True, and False otherwise.
* Return Statement:
The function returns the result of the all() function, indicating whether every element in the list is less than or equal to its adjacent element.
* List Initialization:
lst is initialized with the values [10, 20, 30, 40, 50].
* Function Call:
is_sorted(lst) is called with the list lst.
The result of this function call is True because every element in the list is less than or equal to its adjacent element.
* Result Assignment:
The result of the function call is assigned to the variable result.
* Printing the result with fstring

31. Rotate a list to the left by `n` positions.

In [15]:
def rotate_left(lst, n):           
    rotation_index = n % len(lst)  # Calculate the effective rotation index
    rotated_list = lst[rotation_index:] + lst[:rotation_index]     # Perform the rotation using slicing
    return rotated_list

original_list = [1, 2, 3, 4, 5]
rotated_list = rotate_left(original_list, 2)

print("Original List:", original_list)
print("Rotated List:", rotated_list)


Original List: [1, 2, 3, 4, 5]
Rotated List: [3, 4, 5, 1, 2]


Explanation:

* Function Definition:
def rotate_left(lst, n): defines a function named rotate_left that takes a list lst and an integer n as parameters.
* Calculate Rotation Index:
rotation_index = n % len(lst) calculates the effective rotation index by taking the modulo of n with the length of the list (len(lst)).
This step ensures that the rotation index is within the bounds of the list, handling cases where n is greater than the length of the list.
* Perform Rotation Using Slicing:
rotated_list = lst[rotation_index:] + lst[:rotation_index] creates a new list (rotated_list) by concatenating two slices of the original list:
The first slice (lst[rotation_index:]) starts from the calculated rotation index and goes to the end of the list.
The second slice (lst[:rotation_index]) starts from the beginning of the list and goes up to, but not including, the rotation index.
* Return Rotated List:
return rotated_list returns the rotated list as the result of the function.
* List Initialization:
original_list = [1, 2, 3, 4, 5] initializes a list named original_list with values.
* Function Call:
rotated_list = rotate_left(original_list, 2) calls the rotate_left function with the original_list and a rotation value of 2.
* Print Statements:
print("Original List:", original_list) prints the original list.
print("Rotated List:", rotated_list) prints the rotated list.

32. Rotate a list to the right by `n` positions.

In [22]:
def rotate_right(lst, n):           
    rotation_index = n % len(lst)  # Calculate the effective rotation index
    rotated_list = lst[-rotation_index:] + lst[:-rotation_index]     # Perform the rotation using slicing
    return rotated_list

original_list = [3, 4, 5,1, 2]
rotated_right = rotate_right(original_list, 2)

print("Original List:", original_list)
print("Rotated List:", rotated_right)


Original List: [3, 4, 5, 1, 2]
Rotated List: [1, 2, 3, 4, 5]


Explanation:

* Function Definition:
def rotate_right(lst, n): defines a function named rotate_left that takes a list lst and an integer n as parameters.
* Calculate Rotation Index:
rotation_index = n % len(lst) calculates the effective rotation index by taking the modulo of n with the length of the list (len(lst)).
This step ensures that the rotation index is within the bounds of the list, handling cases where n is greater than the length of the list.
* Perform Rotation Using Slicing:
rotated_list = lst[-rotation_index:] + lst[:-rotation_index] creates a new list (rotated_list) by concatenating two slices of the original list:
The first slice (lst[-rotation_index:]) starts from the calculated negative rotation index and goes to the end of the list.
The second slice (lst[:rotation_index]) starts from the beginning of the list and goes up to, but not including, the negative rotation index.
* Return Rotated List:
return rotated_list returns the rotated list as the result of the function.
* List Initialization:
original_list = [ 3, 4, 5,1, 2] initializes a list named original_list with values.
* Function Call:
rotated_list = rotate_right(original_list, 2) calls the rotate_right function with the original_list and a rotation value of 2.
* Print Statements:
print("Original List:", original_list) prints the original list.
print("Rotated List:", rotated_right) prints the rotated list.

33. Create a list of prime numbers up to 50.

In [7]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def generate_primes(limit):
    prime_list = [num for num in range(2, limit) if is_prime(num)]
    return prime_list

# Example: Generate a list of prime numbers up to 50
limit = 50
primes_up_to_50 = generate_primes(limit)

print("Prime numbers up to", limit, ":", primes_up_to_50)

Prime numbers up to 50 : [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


Explanation:

* is_prime Function:
This function checks whether a given number num is a prime number.
If num is less than 2, it returns False since 0 and 1 are not prime numbers.
It then iterates through the numbers from 2 to the square root of num (converted to an integer) to check if num is divisible by any of them.
If it finds a divisor, it returns False. If no divisors are found, it returns True, indicating that num is a prime number.
* generate_primes Function:
This function generates a list of prime numbers up to a specified limit.
It uses a list comprehension to iterate through numbers from 2 to the given limit and includes only those numbers for which the is_prime function returns True.
The resulting list is a list of prime numbers up to the specified limit.
* Example Usage:
The example sets the limit to 50 and generates a list of prime numbers up to that limit using the generate_primes function.
The result is printed, showing the prime numbers up to 50.

34. Split a list into chunks of size `n`.

In [6]:
def split_chunk_size(list_,size):
    split= [ list_[i:i+size]  for i in range(0,len(list_),size)]
    return split

list_= [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
size= 3

result= split_chunk_size(list_,size)

print('Original List: ', list_)
print('Splitted list :' , result)

Original List:  [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
Splitted list : [[2, 3, 5], [7, 11, 13], [17, 19, 23], [29, 31, 37], [41, 43, 47]]


Explanation:

* split_chunk_size Function:
The function takes two parameters: list_ (the original list) and size (the desired chunk size).
It uses a list comprehension to create chunks of size size from the original list.
The range(0, len(list_), size) generates starting indices for each chunk, and list_[i:i+size] creates a sublist starting from index i up to, but not including, index i + size.
The function returns a list of chunks.
* Example Usage:
The example initializes a list named list_ containing prime numbers.
It specifies a chunk size of 3.
The split_chunk_size function is called with the original list and the chunk size.
The original list and the resulting list of chunks are printed.

35. Find the second largest number in a list.

In [11]:
def second_largest(list_):
    remove_dup=list(set(list_))
    remove_dup.sort(reverse=True)
    return remove_dup[1]

list_= [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 47]
result= second_largest(list_)

print('The second largest number in the list is' , result)

The second largest number in the list is 43


Explanation:

* second_largest Function:
The function takes a list list_ as input.
It removes duplicates from the list by converting it to a set (set(list_)), and then back to a list (list(set(list_))).
The resulting list is sorted in descending order using sort(reverse=True).
The second element (index 1) in the sorted list is returned, representing the second largest number in the original list.
* Example Usage:
The example initializes a list named list_ containing prime numbers with a duplicate (47).
The second_largest function is called with the list.

36. Replace every element in a list with its square.

In [2]:
# Example list
my_list = [2, 4, 6, 8, 10]
squared_list = [i **2 for i in my_list] # Replace every element with its square using a list comprehension
print("Squared list:", squared_list)

Squared list: [4, 16, 36, 64, 100]


Explanation:
* Initialized a variable my_list with a list of int values.
* Used the list comprehension to iterate on every element in the  my_list variable and squared the each single element and updated this into a variable squared_list
* printed the squared_list

37. Convert a list to a dictionary where list elements become keys and their
indices become values.

In [12]:
names=['Jas', 'Abdul', 'Praven', 'Vijay']
converted_type={}
for i, j in enumerate(names):
     converted_type[j]= i
print(converted_type)

{'Jas': 0, 'Abdul': 1, 'Praven': 2, 'Vijay': 3}


Explanation:
    
* Created a variable "names" with list of names in it.
* Created a empty dictionary to store the values from the loop iteration.
* Iterating every names from the list and using the enumerate method, the enumerate () method adds a counter to an iterable and returns it in the form of an enumerating object. 
* Updating the keys and values to the empty dictionary we created before. Printing the converted_type to check the list of names are in keys now and the values are their index.

38. Shuffle the elements of a list randomly.

In [13]:
import random
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
random.shuffle(my_list)
print("Shuffled list:", my_list)

Shuffled list: [8, 6, 7, 3, 10, 2, 4, 1, 9, 5]


Explanation: 
* Importing the random module which as the inbuilt function for shuffle
* creating a list of numbers arranged from 1-10
* using the random.shuffle() method, this will randomly shuffle the elements in the list. 
* Finally printing our shuffled list variable.

39. Create a list of the first 10 factorial numbers.

In [10]:
def factorial (n):
    if n == 0 or n ==1:
        return 1
    return n * factorial(n-1)

factorial_numbers= [factorial(number) for number in range(10)]
factorial_numbers

[1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880]

Explanation:

* Function Definition:
The function factorial takes a single parameter n.
It uses recursion to calculate the factorial of n.
The base case checks if n is 0 or 1, in which case the function returns 1.
Otherwise, it returns n multiplied by the factorial of (n-1).
* List Comprehension:
The line factorial_numbers = [factorial(number) for number in range(10)] creates a list called factorial_numbers.
It uses a list comprehension to calculate the factorial of each number in the range from 0 to 9 (10 is exclusive) using the factorial function.
* Result:
The factorial_numbers list will contain the factorials of numbers from 0 to 9.

40. Check if two lists have at least one element in common.

In [5]:
def common_element(a,b):
    for i in a:
        if i in b:
            return True
    return false
        
a= ['apple', 'banana', 'orange','mango']
b= ['pineapple', 'avacodo', 'orange', 'orange', 'apple', 'mango','pineapple']
print('Does the list has atleas one common element :',common_element(a,b))

Does the list has atleas one common element : True


Explanation

* Function Definition:
The function common_element takes two lists, a and b, as parameters.
It uses a for loop to iterate over each element (i) in the first list a.
Inside the loop, it checks if the current element i is present in the second list b using the in keyword.
If a common element is found, the function immediately returns True.
If the loop completes without finding any common element, it returns False.
* Lists:
Two lists, a and b, are defined. These lists contain strings representing different fruits.
* Function Call:
The common_element function is called with the lists a and b as arguments.
The result (either True or False) is printed along with a descriptive message.
* Output:
The function checks if there is at least one common element between the two lists (a and b).

41. Remove all elements from a list.

In [9]:
fruits= ['apple', 'banana', 'orange','mango']
fruits.clear()
print(fruits)

[]


Explanation:

- Created a variable called fruits with lits of fruits   
- used the clear() method in list function to clear all the element in the list 

42. Replace negative numbers in a list with 0.

In [26]:
numbers= [1,-2,3,4,5,-4]
new_numbers=[0 if i < 0 else i for i in numbers]
print(f'''Original numbers :{numbers}
replaced numbers : {new_numbers}''')

Original numbers :[1, -2, 3, 4, 5, -4]
replaced numbers : [1, 0, 3, 4, 5, 0]


Explanation:

* List Comprehension:
The line new_numbers = [0 if i < 0 else i for i in numbers] uses list comprehension.
It iterates through each element (i) in the original numbers list.
If the element is negative (i < 0), it appends 0 to the new list; otherwise, it appends the original element i.
* Print Statement:
The print statement outputs both the original list (numbers) and the modified list (new_numbers).
It uses an f-string for formatting.


43. Convert a string into a list of words.

In [27]:
my_string = "Hello, this is a sample sentence."
word_list = my_string.split()
print("List of words:", word_list)

List of words: ['Hello,', 'this', 'is', 'a', 'sample', 'sentence.']


Explanation:

* String Splitting:
The line word_list = my_string.split() uses the split() method on the string my_string.
This method splits the string into a list of words, using whitespace as the default delimiter.
* Print Statement:
The print("List of words:", word_list) statement outputs a message along with the list of words.
It uses an f-string to format the output.

44. Convert a list of words into a string.

In [32]:
List_of_words= ['Hello,', 'this', 'is', 'a', 'sample', 'sentence.']
joined_words= ' '.join(List_of_words)
print(joined_words)

Hello, this is a sample sentence.


Explanation:

* List Joining:
The line joined_words = ' '.join(List_of_words) uses the join() method to concatenate the elements of List_of_words into a single string.
The string ' ' is used as the separator, indicating that a space should be inserted between each pair of joined words.
* Print Statement:
The print(joined_words) statement outputs the result of the joining operation.
* Output:
The output displays the string obtained by joining the elements of List_of_words with spaces.

45. Create a list of the first `n` powers of 2.

In [4]:
n=5
result= [2**i for i in range(n)]
print("List of the first", n, "powers of 2:",result)

[1, 2, 4, 8, 16]


Explanation:
    
* List Comprehension:
The line result = [2**i for i in range(n)] uses list comprehension.
It iterates over the range from 0 to n-1 and calculates 2**i for each i.
The result is a list containing the first n powers of 2.
* Print Statement:
The print(result) statement outputs the list of powers of 2.

46. Find the longest string in a list of strings.

In [12]:
fruits= ['apple', 'banana', 'orange','mango', 'watermelon']
longest_sting=''
for i in fruits:
    if len(i) >len(longest_sting):
        longest_sting= i
print('The longest string in the list is', longest_sting)

The longest string in the list is watermelon


Explanation:

* Initialization:
The line fruits = ['apple', 'banana', 'orange', 'mango', 'watermelon'] initializes a list named fruits with strings representing different fruits.
The line longest_sting = '' initializes an empty string named longest_sting. This will be used to store the longest string found in the fruits list.
* For Loop:
The for loop iterates over each element (i) in the fruits list.
* Condition:
Inside the loop, the if statement checks if the length of the current element i is greater than the length of the current longest_sting.
If true, it updates longest_sting to be the current element i.
* Print Statement:
The print('The longest string in the list is', longest_sting) statement outputs the result.
It indicates the longest string found in the fruits list.

47. Find the shortest string in a list of strings.

In [17]:
fruits= ['apple', 'banana', 'orange','mangoes', 'watermelon']
shortest_sting=fruits[0]
for i in fruits:
    if len(i) <len(shortest_sting):
        shortest_sting= i
print('The Shortest string in the list is', shortest_sting)

The Shortest string in the list is apple


Explanation:

* Initialization:
The line fruits = ['apple', 'banana', 'orange', 'mangoes', 'watermelon'] initializes a list named fruits with strings representing different fruits.
The line shortest_sting = fruits[0] initializes shortest_sting with the first string in the fruits list. This will be used to store the shortest string found in the list.
* For Loop:
The for loop iterates over each element (i) in the fruits list.
* Condition:
Inside the loop, the if statement checks if the length of the current element i is less than the length of the current shortest_sting.
If true, it updates shortest_sting to be the current element i.
* Print Statement:
The print('The Shortest string in the list is', shortest_sting) statement outputs the result.
It indicates the shortest string found in the fruits list.

48. Create a list of the first `n` triangular numbers.

In [30]:
def triangular_numbers(n):
    return [i * (i + 1) // 2 for i in range(1, n + 1)]
n = 5
triangular_list = triangular_numbers(n)
print("List of the first", n, "triangular numbers:", triangular_list)

List of the first 5 triangular numbers: [1, 3, 6, 10, 15]


Explanation:

* Function Definition:
The function triangular_numbers(n) takes a parameter n.
It uses a list comprehension to generate a list of the first n triangular numbers.
The formula for the triangular number at position i is i * (i + 1) // 2
The function returns the list of triangular numbers.
* Function Call:
The line n = 5 sets the value of n to 5.
The line triangular_list = triangular_numbers(n) calls the triangular_numbers function with n as an argument and stores the result in the variable triangular_list.
* Print Statement:
The line print("List of the first", n, "triangular numbers:", triangular_list) outputs the result.
It displays a message along with the list of the first n triangular numbers.

49. Check if a list contains another list as a subsequence.

In [34]:
def is_subsequence(subsequence, main_list):
    subseq_index = 0  
    for element in main_list:
        if element == subsequence[subseq_index]:
            subseq_index += 1
            if subseq_index == len(subsequence):
                return True
    return False

main_list = ['apple', 'orange', 'watermelon', 'pineapple', 'grapes', 'nuts']
subsequence = ['orange', 'grapes',  'nuts']

if is_subsequence(subsequence, main_list):
    print("Main list contains the subsequence.")
else:
    print("Main list does not contain the subsequence.")

Main list contains the subsequence.


Explanation: 

* Function Definition:
The function is_subsequence(subsequence, main_list) checks if main_list contains the elements of subsequence in the same order.
It uses a loop to iterate through each element in main_list.
If an element in main_list matches the current element in subsequence, it continues checking the next elements in both lists.
If all elements of subsequence are found in order within main_list, the function returns True; otherwise, it returns False.
* Lists Initialization:
The line main_list = ['apple', 'orange', 'watermelon', 'pineapple', 'grapes', 'nuts'] initializes a list named main_list.
The line subsequence = ['orange', 'grapes', 'nuts'] initializes a list named subsequence.
* Function Call:
The line if is_subsequence(subsequence, main_list): calls the is_subsequence function with subsequence and main_list as arguments.
Depending on the result, it prints whether the main list contains the subsequence or not.

50. Swap two elements in a list by their indices.

In [3]:
my_list = [1, 2, 3, 4, 5]
index1 = 1
index2 = 3
temp = my_list[index1]  # Swap the elements at the specified indices
my_list[index1] = my_list[index2]
my_list[index2] = temp
print("List after swapping elements:", my_list)

List after swapping elements: [1, 4, 3, 2, 5]


Explanation:

* List and Indices:
The line my_list = [1, 2, 3, 4, 5] initializes a list named my_list with integer elements.
The variables index1 and index2 are set to 1 and 3, respectively. These are the indices of the elements to be swapped.
* Swapping Elements:
The line temp = my_list[index1] temporarily stores the value at index index1.
The line my_list[index1] = my_list[index2] assigns the value at index index2 to the position of index index1.
The line my_list[index2] = temp assigns the temporarily stored value to the position of index index2.
These operations effectively swap the elements at the specified indices.
* Print Statement:
The line print("List after swapping elements:", my_list) outputs the result.
It displays the modified list after swapping the elements.

# Tuple Based Practice Problem :

1. Create a tuple with integers from 1 to 5.

In [6]:
_tuple = (1, 2, 3, 4, 5)
print(_tuple)

(1, 2, 3, 4, 5)


- Used parentheses to create a tuple named _tuple containing the integers from 1 to 5.
- print the tuple using the print() statement.

2. Access the third element of a tuple.

In [5]:
my_tuple = (10, 20, 30, 40, 50)
third_element = my_tuple[2]
print("The third element of the tuple is:", third_element)

The third element of the tuple is: 30


- Created a tuple named my_tuple with five elements: 10, 20, 30, 40, and 50.
- To access elements of a tuple, we use square brackets [] with the index of the element we want to access. Tuples are zero-indexed, so the third element has an index of 2.
- We store the value of the third element (30) in the variable third_element.
- Finally, we use the print function to display a message along with the value of the third element of the tuple.

3. Find the length of a tuple without using the `len()` function.

In [1]:
my_tuple = (10, 20, 30, 40, 50)
count = 0
for i in my_tuple:
    count += 1
print(count)

5


Explanation:

* Tuple and Initialization:
The line my_tuple = (10, 20, 30, 40, 50) creates a tuple named my_tuple with integer elements.
The variable count is initialized to 0. This variable will be used to count the number of elements in the tuple.
* For Loop:
The for loop iterates over each element (i) in the my_tuple.
Inside the loop, the count += 1 statement increments the count for each element encountered in the tuple.
* Print Statement:
The line print(count) outputs the result.
It displays the final count, representing the number of elements in the tuple.

4. Count the occurrences of an element in a tuple.

In [3]:
my_tuple = (10, 20, 30, 20, 40, 50, 20)
element_to_count = 20
count = 0
for item in my_tuple: # Iterate through the tuple and count occurrences of the chosen element
    if item == element_to_count:
        count += 1
print(f"The element {element_to_count} appears {count} times in the tuple.")

The element 20 appears 3 times in the tuple.


Explanation: 
    
* Tuple and Initialization:
The line my_tuple = (10, 20, 30, 20, 40, 50, 20) creates a tuple named my_tuple with integer elements.
The variable element_to_count is set to 20. This variable represents the element for which the occurrences will be counted.
The variable count is initialized to 0. This variable will be used to count the occurrences of the chosen element.
* For Loop:
The for loop iterates over each element (item) in the my_tuple.
Inside the loop, the if statement checks if the current element (item) is equal to the chosen element to count (element_to_count).
If true, it increments the count by 1 for each occurrence of the chosen element.
* Print Statement:
The line print(f"The element {element_to_count} appears {count} times in the tuple.") outputs the result.
It displays a message indicating the number of times the chosen element appears in the tuple.

5. Find the index of the first occurrence of an element in a tuple.

In [4]:
my_tuple = (10, 20, 30, 20, 40, 50)
element_to_find = 20
index = -1  # Initialize with -1 to indicate that the element was not found
for i, item in enumerate(my_tuple):
    if item == element_to_find:
        index = i
        break  # Exit the loop once the first occurrence is found
if index != -1: # Print the index of the first occurrence
    print(f"The first occurrence of {element_to_find} is at index {index}.")
else:
    print(f"{element_to_find} is not found in the tuple.")

The first occurrence of 20 is at index 1.


Explanation: 

* Tuple and Initialization:
The line my_tuple = (10, 20, 30, 20, 40, 50) creates a tuple named my_tuple with integer elements.
The variable element_to_find is set to 20. This variable represents the element to be searched for.
The variable index is initialized to -1. This variable will be used to store the index of the first occurrence of the element, or -1 if the element is not found.
* For Loop with Enumeration:
The for loop iterates over each element (item) in the my_tuple along with its index (i).
Inside the loop, the if statement checks if the current element (item) is equal to the element to be found (element_to_find).
If true, it updates the index with the current index (i) and exits the loop using break.
* Print Statement:
The lines if index != -1: and print(f"The first occurrence of {element_to_find} is at index {index}.") handle the output.
If the element is found (index != -1), it prints the message with the index.
If the element is not found, it prints a message indicating that.

6. Check if an element exists in a tuple.

In [10]:
def check(tuple_, element):
    if element in tuple_:
        return f"{element} exists in the tuple."
    return f"{element} does not exist in the tuple."
tuple_= (10, 20, 30, 20, 40, 50)
element= 40

check(tuple_, element)

'40 exists in the tuple.'

Explanation: 

* Function Definition:
The function check(tuple_, element) takes two parameters: tuple_ (the tuple to be checked) and element (the element to be checked for).
Inside the function, it uses the in operator to check if the specified element is present in the given tuple.
If the element is found in the tuple, it returns a message indicating that the element exists in the tuple. Otherwise, it returns a message indicating that the element does not exist in the tuple.
* Function Call:
The line check(tuple_, element) calls the check function with the provided tuple and element as arguments.

7. Convert a tuple to a list.

In [20]:
tuple_= (10, 20, 30, 20, 40, 50)
list_= list(tuple_)

print(f'''Before : {tuple_} its type {type(tuple_)}
After : {list_} its type {type(list_)}''')

Before : (10, 20, 30, 20, 40, 50) its type <class 'tuple'>
After : [10, 20, 30, 20, 40, 50] its type <class 'list'>


Explanation:

* Created a tuple with list of int values and assigend to variable called tuple_
* Used the list() method to type cast the tuple into list 
* printed the before and after of list and tuple along with its type using f-string.

8. Convert a list to a tuple.

In [21]:
list_= [10, 20, 30, 20, 40, 50] 
tuple_= tuple(tuple_)

print(f'''Before : {list_} its type {type(list_)}
After : {tuple_} its type {type(tuple_)}''')

Before : [10, 20, 30, 20, 40, 50] its type <class 'list'>
After : (10, 20, 30, 20, 40, 50) its type <class 'tuple'>


Explanation:

* Created a list with list of int values and assigend to variable called list_
* Used the tuple() method to type cast the list into tuple 
* printed the before and after of list and tuple along with its type using f-string.

9. Unpack the elements of a tuple into variables.

In [28]:
my_tuple = (10, 20, 30)
var1, var2, var3 = my_tuple   # Unpack the elements of the tuple into variables

print("var1:", var1) # Print the variables
print("var2:", var2)
print("var3:", var3)

var1: 10
var2: 20
var3: 30


Explanation:

- Tuple and Unpacking:
The line my_tuple = (10, 20, 30) creates a tuple named my_tuple with three integer elements.
The line var1, var2, var3 = my_tuple unpacks the elements of the tuple into three variables (var1, var2, and var3).
Each variable is assigned the corresponding value from the tuple.
- Print Statements:
The lines print("var1:", var1), print("var2:", var2), and print("var3:", var3) output the result.
They display the values of the variables var1, var2, and var3, respectively.

10. Create a tuple of even numbers from 1 to 10.

In [33]:
even_numbers_list = [num for num in range(2, 11, 2)]  # Start from 2, step by 2, end at 10
even_numbers_tuple = tuple(even_numbers_list)   #Convert the list to a tuple

print("Tuple of even numbers:", even_numbers_tuple)

Tuple of even numbers: (2, 4, 6, 8, 10)


Explanation:

- List Comprehension:
The line even_numbers_list = [num for num in range(2, 11, 2)] creates a list named even_numbers_list using list comprehension.
It generates even numbers starting from 2, with a step of 2, up to (but not including) 11.
- Tuple Conversion:
The line even_numbers_tuple = tuple(even_numbers_list) converts the list even_numbers_list to a tuple named even_numbers_tuple.
This is achieved by using the tuple() constructor, which takes an iterable (in this case, a list) and creates a tuple.
- Print Statement:
The line print("Tuple of even numbers:", even_numbers_tuple) outputs the result.
It displays a message along with the tuple of even numbers.

11. Create a tuple of odd numbers from 1 to 10.

In [35]:
odd_numbers_list = [num for num in range(1, 11, 2)]  # Start from 1, step by 2, end at 11
odd_numbers_tuple = tuple(odd_numbers_list)  # Convert the list to a tuple

print("Tuple of odd numbers:", odd_numbers_tuple)

Tuple of odd numbers: (1, 3, 5, 7, 9)


Explanation:

- The list comprehension [num for num in range(1, 11, 2)] generates odd numbers starting from 1, with a step of 2, up to (but not including) 11.
- The tuple() constructor converts the list to a tuple.
- The print statement displays the message along with the tuple of odd numbers.

12. Concatenate two tuples.

In [37]:
tuple1= (1,3,4,5,6)
tuple2= (7,8,9,10,11)
concatenated_tuple= tuple1+tuple2
print(concatenated_tuple)

(1, 3, 4, 5, 6, 7, 8, 9, 10, 11)


Explanation : 
    
- Tuple Initialization:
The lines tuple1 = (1, 3, 4, 5, 6) and tuple2 = (7, 8, 9, 10, 11) initialize two tuples named tuple1 and tuple2 with integer elements.
- Concatenation:
The line concatenated_tuple = tuple1 + tuple2 concatenates the two tuples using the + operator.
This creates a new tuple named concatenated_tuple that contains all the elements from tuple1 followed by all the elements from tuple2.
- Print Statement:
The line print(concatenated_tuple) outputs the result.
It displays the concatenated tuple.

13. Repeat a tuple three times.

In [39]:
tuple_= (1,3,4,5,6)
repeated_tuple= tuple_*3
print("Repeated tuple:", repeated_tuple)

Repeated tuple: (1, 3, 4, 5, 6, 1, 3, 4, 5, 6, 1, 3, 4, 5, 6)


- We start by creating a tuple named tuple_ with some elements.
- We use the * operator to repeat the tuple three times, resulting in a new tuple named repeated_tuple.
- We print the repeated tuple.

14. Check if a tuple is empty.

In [4]:
def check(tuple_):
    if tuple_:
        return('The given tuple is not empty')
    else:
        return('The given tuple is empty')

tuple_= (1,3,4,5,6)
tuple3=()
print( check(tuple_)) # printing the function wi
print( check(tuple3))

The given tuple is not empty
The given tuple is empty


Explanation :
    
* Function Definition:
The function check(tuple_) takes a single parameter tuple_.
Inside the function, it checks if the given tuple is truthy (non-empty) using an if statement.
If the tuple is truthy, it returns a message indicating that the tuple is not empty. Otherwise, it returns a message indicating that the tuple is empty.
* Tuple Initialization:
The line tuple_ = (1, 3, 4, 5, 6) initializes a tuple named tuple_ with integer elements.
The line tuple3 = () initializes an empty tuple named tuple3.
* Function Calls:
The lines print(check(tuple_)) and print(check(tuple3)) call the check function with the provided tuples as arguments.

15. Create a nested tuple.

In [1]:
nested_tuple = ((1, 2, 3), ('a', 'b', 'c'), (True, False))

print("Nested tuple:", nested_tuple)

Nested tuple: ((1, 2, 3), ('a', 'b', 'c'), (True, False))


- We create a nested tuple named nested_tuple that contains three tuples as its elements. Each of these inner tuples can have different data types.
- We print the nested tuple to see its structure.

16. Access the first element of a nested tuple.

In [5]:
nested_tuple = ((1, 2, 3), (4, 5, 6), (7, 8, 9))

first_element = nested_tuple[0][0]

print("First element of the nested tuple:", first_element)

First element of the nested tuple: 1


Explanation:

* Nested Tuple Initialization:
The line nested_tuple = ((1, 2, 3), (4, 5, 6), (7, 8, 9)) initializes a nested tuple named nested_tuple.
* Accessing the First Element:
The expression nested_tuple[0] accesses the first tuple within the nested tuple.
The additional [0] at the end accesses the first element of that first tuple.
* Print Statement:
The line print("First element of the nested tuple:", first_element) outputs the result.
It displays the first element of the nested tuple.

17. Create a tuple with a single element.

In [8]:
single_element_tuple = (2,) 

print("Single element tuple:", single_element_tuple)

Single element tuple: (2,)


- We create a tuple named single_element_tuple with a single element. The key here is to include a trailing comma after the element, which informs Python that you want to create a tuple with one element.
- We print the single element tuple to see its contents.

18. Compare two tuples.

In [13]:
tuple1 = (1, 2, 3)
tuple2=(4, 5, 6)

''' The six comparison operators are:
== or equal to,
!= or not equal to,
> or greater than,
>= or greater than or equal to,
< or less than, and.
<= or less than or equal to.'''

print("tuple1 == tuple2:", tuple1 == tuple2)  
print("tuple1 != tuple2:", tuple1 != tuple2)  
print("tuple1 < tuple2:", tuple1 < tuple2)  
print("tuple1 <= tuple2:", tuple1 <= tuple2) 
print("tuple1 > tuple2:", tuple1 > tuple2)   
print("tuple1 >= tuple2:", tuple1 >= tuple2) 



tuple1 == tuple2: False
tuple1 != tuple2: True
tuple1 < tuple2: True
tuple1 <= tuple2: True
tuple1 > tuple2: False
tuple1 >= tuple2: False


Created two tuples named tuple1 and tuple2.
And used various comparison operators to compare the elements of the two tuples:
- tuple1 == tuple2 checks if the tuples are equal element-wise.
- tuple1 != tuple2 checks if the tuples are not equal element-wise.
- tuple1 < tuple2 checks if tuple1 is lexicographically less than tuple2.
- tuple1 <= tuple2 checks if tuple1 is lexicographically less than or equal to tuple2.
- tuple1 > tuple2 checks if tuple1 is lexicographically greater than tuple2.
- tuple1 >= tuple2 checks if tuple1 is lexicographically greater than or equal to tuple2.

19. Delete a tuple.

In [19]:
tuple_ = (1, 2, 3)

del tuple_


print(tuple_)

NameError: name 'tuple_' is not defined

* Created a Tuple with variable tuple_
* Since tuples are immutable, their elements cannot be modified or removed once the tuple is created. Hence used the del keyword in python and deleted the variable tuple_. 
* Now tried accessing the tuple it showing name error since it was deleted.

20. Slice a tuple.

In [22]:
names = ('Jas', 'Vik', 'Mark', 'Siva','Vijay')
sliced= names[1:4]
print(sliced)

('Vik', 'Mark', 'Siva')


* Created a tuple with list of names
* Created variable silced using the slicing operation [1:4] it will slice the tuple from 1st index upto 3rd index.
* Printing the sliced variable

21. Find the maximum value in a tuple.

In [24]:
_tuple = (10, 20, 5, 45, 30)
max_=max(_tuple)
print('The Maximum value in the tuple is ',max_)

The Maximum value in the tuple is  45


* Initiated a variable _tuple with list of int values
* used the max function and pass the tuple inside it to see the max value and storing it in the variable max_
* printing the max value with the string using f-string method

22. Find the minimum value in a tuple.

In [25]:
_tuple = (10, 20, 5, 45, 30)
min_=min(_tuple)
print('The Minimum value in the tuple is ',min_)

The Minimum value in the tuple is  5


* Initiated a variable _tuple with list of int values
* used the min function and pass the tuple inside it to see the minimum value and storing it in the variable min_
* printing the min value with the string using f-string method

23. Convert a string to a tuple of characters.

In [28]:
my_string = "Hello, World!"
tuple_of_characters = tuple(my_string)
print("Tuple of characters:", tuple_of_characters)

Tuple of characters: ('H', 'e', 'l', 'l', 'o', ',', ' ', 'W', 'o', 'r', 'l', 'd', '!')


- Initiated a variable my_string with string.
- We use the tuple() constructor and pass the string my_string as an argument. This constructor converts the string into a tuple of individual characters.
- We print the resulting tuple of characters.

24. Convert a tuple of characters to a string.

In [31]:
tuple_=('H', 'e', 'l', 'l', 'o', ',', ' ', 'W', 'o', 'r', 'l', 'd', '!')
string= ''.join(tuple_)
print(string)

Hello, World!


- Created a tuple named tuple_ containing individual characters.
- Used the join() method, which is called on an empty string (''), to join the characters from the tuple and create a single string.
- print the resulting string.

25. Create a tuple from multiple data types.

In [33]:
mixed_tuple = (1, "hello", 3.14, True)

print(mixed_tuple)

(1, 'hello', 3.14, True)


- The mixed_tuple contains four elements of different data types: an integer, a string, a float, and a boolean. 

26. Check if two tuples are identical.

In [34]:
tuple1 = (1, 2, 3)
tuple2 = (1, 2, 3)

if tuple1 == tuple2:
    print("Tuples are identical")
else:
    print("Tuples are not identical")

Tuples are identical


* Initiated two tuples , and used the if class and the == operator is used to compare tuple1 and tuple2. 
* If the elements in both tuples are the same and in the same order, the condition will be true, and it will print "Tuples are identical." Otherwise, it will print "Tuples are not identical."

27. Sort the elements of a tuple.

In [38]:
tuple_ = (10, 2, 3, 5, 11, 1)
sorted_tuple = tuple(sorted(tuple_))
print(sorted_tuple)      

(1, 2, 3, 5, 10, 11)


- We start by creating a tuple named tuple_ with some numeric elements.
- We use the sorted() function to sort the elements of the tuple. The sorted() function returns a sorted list.
- We use the tuple() constructor to convert the sorted list back into a tuple.
- We print the sorted tuple.

28. Convert a tuple of integers to a tuple of strings.

In [1]:
tuple_ = (10, 2, 3, 5, 11, 1)
tuple_of_strings = tuple(str(item) for item in tuple_)
tuple_of_strings

('10', '2', '3', '5', '11', '1')

* Initated a variable tuple_ with list of integers
* Used list comprehension to iterate through each integer in the tuple and convert it to a string using the str() function. The list comprehension generates a list of strings.
* Then convert the list of strings to a tuple using the tuple() constructor.
* Finally print the resulting tuple of strings.

29. Convert a tuple of strings to a tuple of integers.

In [11]:
tuple_ = ('10', '2', '3', '5', '11', '1')
tuple_of_int = tuple(int(item) for item in tuple_)
tuple_of_int

(10, 2, 3, 5, 11, 1)

* Initated a variable tuple_ with list of strings
* Used list comprehension to iterate through each string in the tuple and convert it to a int using the int() function. The list comprehension generates a list of int.
- Then convert the list of int to a tuple using the tuple() constructor.
- Finally print the resulting tuple of integers.

30. Merge two tuples.

In [12]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

merged_tuple = tuple1 + tuple2

print("Merged tuple:", merged_tuple)

Merged tuple: (1, 2, 3, 4, 5, 6)


- We start by creating two tuples named tuple1 and tuple2.
- We use the + operator to merge the two tuples, resulting in a new tuple named merged_tuple.
- We print the merged tuple.

31. Flatten a nested tuple.

In [3]:
def flatten(tuple_):
    flaten=[]
    for i in tuple_:
        if isinstance(i,tuple):
            flaten.extend(flatten(i))
        else:
            flaten.append(i)
    return tuple(flaten)
tuple_=((1, 2), (3, 4, 5), (6, (7, 8)))
print(flatten(tuple_))

(1, 2, 3, 4, 5, 6, 7, 8)


* Function Definition:
The flatten function takes a tuple as an argument.
* Initialization:
It initializes an empty list flaten to store the flattened elements.
* Iteration through Tuple Elements:
It iterates through each element i in the input tuple_.
* Checking if Element is a Tuple:
It checks if the current element i is an instance of a tuple using isinstance(i, tuple).
If it is a tuple, it recursively calls flatten(i) to flatten the nested tuple.
* Extending the List:
The extend method is used to add the flattened elements to the flaten list.
* Appending Non-Tuple Elements:
If the current element i is not a tuple, it is appended directly to the flaten list.
* Conversion to Tuple:
Finally, the function returns a new tuple created from the flattened list using tuple(flaten).
* Example Usage:
The given example has a nested tuple ((1, 2), (3, 4, 5), (6, (7, 8))).
The function is called with this tuple, and the flattened result is printed.

32. Create a tuple of the first 5 prime numbers.

In [14]:
def is_prime(num):
    if num <2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

prime_numbers_list=tuple([i for i in range(2,100) if is_prime(i)][:5])
prime_numbers_list

(2, 3, 5, 7, 11)

* def is_prime(num):
This defines a function named is_prime that takes a number num as an argument.
* if num < 2:
Checks if num is less than 2. If so, it returns False since prime numbers are defined as integers greater than 1.
* for i in range(2, int(num**0.5) + 1):
Iterates through the numbers from 2 to the integer square root of num (inclusive). This loop is used to check if num has any divisors other than 1 and itself.
* if num % i == 0:
Checks if num is divisible evenly by the current value of i. If so, num has a divisor other than 1 and itself, making it not a prime number. In this case, the function returns False.
return True
If the function has not returned False during the loop, it means that no divisors were found. Therefore, the function returns True, indicating that num is a prime number.
* prime_numbers_list = tuple([i for i in range(2,100) if is_prime(i)][:5])
Creates a tuple containing the first 5 prime numbers on range 2-99.
Uses a list comprehension to iterate over the numbers from 2 to 99 and includes only those that are prime (using the is_prime function).
Limits the result to the first 5 prime numbers by using [:5].
Converts the resulting list to a tuple.
* prime_numbers_list
Finally, the tuple containing the first 5 prime numbers is printed.

33. Check if a tuple is a palindrome.

In [24]:
def is_palindrome(tuple_):
    return tuple_ == tuple_[::-1]

result = is_palindrome((1, 2, 3, 2, 1))

if result:
    print('The tuple is a palindrome')
else:
    print('The tuple is not a palindrome')

The tuple is a palindrome


- The is_palindrome function compares the given tuple (tuple_) to its reversed version (tuple_[::-1]).
- The result is a boolean indicating whether the tuple is a palindrome or not.
- Finally we checks if the tuple (1, 2, 3, 2, 1) is a palindrome and prints the corresponding message.

34. Create a tuple of squares of numbers from 1 to 5.

In [32]:
def squares(n):
    result=[]
    for i in range(1,n+1):
        result.append(i**2)
    return tuple(result)


print('The tuple of Squares of numbers from 1 to 5 :', squares(5))
        

The tuple of Squares of numbers from 1 to 5 : (1, 4, 9, 16, 25)


* Function Definition:
def squares(n):: Defines a function named squares that takes an integer n as an argument.
* Initialization of result List:
result = []: Initializes an empty list named result to store the squares of numbers.
* For Loop to Calculate Squares:
for i in range(1, n + 1):: Iterates through numbers from 1 to n (inclusive).
* Appending Squares to result:
result.append(i ** 2): Calculates the square of each number i and appends it to the result list.
* Returning Result as a Tuple:
return tuple(result): Converts the result list to a tuple and returns it.
* Example Usage:
print('The tuple of Squares of numbers from 1 to 5:', squares(5)): Calls the squares function with n=5 and prints the result.

35. Filter out all even numbers from a tuple.

In [40]:
_tuple=(1,2,3,4,5,6,7,8,9,10,12)
even_tuple=tuple( i for i in _tuple if i%2==0 )
print(even_tuple)

(2, 4, 6, 8, 10, 12)


* Tuple Initialization:
_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12)
Initializes a tuple named _tuple with the values 1 to 12.
* List Comprehension for Filtering Even Numbers:
even_tuple = tuple(i for i in _tuple if i % 2 == 0)
Uses a list comprehension to iterate over elements in _tuple.
Filters only the even numbers by checking i % 2 == 0.
Converts the resulting list to a tuple and assigns it to the variable even_tuple.
* Printing the Result:
print(even_tuple)
Prints the tuple containing only the even numbers.

36. Multiply all elements in a tuple by 2.

In [43]:
_tuple=(1,2,3,4,5)
multiplied_tuple=tuple(i *2 for i in _tuple )
print(multiplied_tuple)

(2, 4, 6, 8, 10)


* Tuple Initialization:
_tuple = (1, 2, 3, 4, 5)
Initializes a tuple named _tuple with the values 1 to 5.
* List Comprehension for Multiplying Each Element by 2:
multiplied_tuple = tuple(i * 2 for i in _tuple)
Uses a list comprehension to iterate over elements in _tuple.
Multiplies each element by 2 (i * 2).
Converts the resulting list to a tuple and assigns it to the variable multiplied_tuple.
* Printing the Result:
print(multiplied_tuple)
Prints the tuple containing each element of _tuple multiplied by 2.

37. Create a tuple of random numbers.

In [56]:
import random
random_num=tuple( random.randint(1, 100) for i in range (10))
print('Tuple of random numbers:',random_num)

Tuple of random numbers: (86, 7, 4, 81, 22, 15, 44, 74, 67, 31)


* Importing the random Module:
import random
Imports the random module in Python, which provides functions for generating random numbers.
* Generating a Tuple of Random Numbers:
random_num = tuple(random.randint(1, 100) for i in range(10))
Uses a list comprehension to generate 10 random integers between 1 and 100 using random.randint(1, 100).
Converts the resulting list to a tuple and assigns it to the variable random_num.
* Printing the Result:
print('Tuple of random numbers:', random_num)
Prints the tuple containing the 10 random numbers.

38. Check if a tuple is sorted.

In [67]:
tuple_=(86, 7, 4, 81, 22, 15, 44, 74, 67, 31)

if tuple_ == tuple(sorted(tuple_)):
    print('Tuple is sorted')
else:
    print('Tuple is not sorted')

Tuple is not sorted


Explanation:
* Initialized a tuple_ with random values
* Using the if condition and using the sorted inbuilt function and type cast into the tuple () and check if that is equal to the tuple_
* If both are equal it will print Tuple is sorted else print tuple is not sorted

39. Rotate a tuple to the left by `n` positions.

In [4]:
def rotate_tuple(tuple_, n):
    rotated_tuple= tuple_[n:]+tuple_[:n]
    return rotated_tuple
        
tuple_=(86, 7, 4, 81, 22, 15, 44, 74, 67, 31)
n=2

print(rotate_tuple(tuple_, n))

(4, 81, 22, 15, 44, 74, 67, 31, 86, 7)


Explanation: 

* Created a function rotate_tuple with arguments (tuple_ , n)  tuple_ will pass the tuple argument, n is the position which we want to rotate.
* created a variable rotated_tuple where we using the tuple indexing start from the nth position till last index and concatenate start index till nth position (excluding nth index). Returning the rotated_tuple variable
* Created a variable for passing tuple_ with integers and assigned the nth posstion.
* Printing the function rotate_tuple(tuple_,n)

40. Rotate a tuple to the right by `n` positions.

In [5]:
def rotate_tuple(tuple_, n):
    rotated_tuple= tuple_[-n:]+tuple_[:-n]
    return rotated_tuple
        
tuple_=(86, 7, 4, 81, 22, 15, 44, 74, 67, 31)
n=2

print(rotate_tuple(tuple_, n))

(67, 31, 86, 7, 4, 81, 22, 15, 44, 74)


Explanation: 

* Created a function rotate_tuple with arguments (tuple_ , n)  tuple_ will pass the tuple argument, n is the position which we want to rotate.
* created a variable rotated_tuple assigning the concatenating values tuple_[-n:] extracts the last n elements of the tuple.tuple_[:-n] extracts all elements from the beginning of the tuple up to (but not including) the last n elements.The concatenation of these two slices creates the rotated tuple to the right.
* Returning the rotated_tuple variable
* Created a variable for passing tuple_ with integers and assigned the nth posstion.
* Printing the function rotate_tuple(tuple_,n)

41. Create a tuple of the first 5 Fibonacci numbers.

In [15]:
def fibonacci(n):
    start=[0,1]
    while len(start)<n:
        fibbi= start[-1]+ start[-2]
        start.append(fibbi)
    return tuple(start)

print(fibonacci(5))

(0, 1, 1, 2, 3)


Explanation:

* Initialization:
start = [0, 1]: Initializes a list called start with the first two Fibonacci numbers, 0 and 1.
* Fibonacci Number Generation:
while len(start) < n:: This loop continues until the length of the start list reaches the specified value n.
fibbi = start[-1] + start[-2]: Calculates the next Fibonacci number by adding the last two elements of the start list.
start.append(fibbi): Appends the newly calculated Fibonacci number to the start list.
* Conversion to Tuple:
return tuple(start): Converts the final start list into a tuple and returns it.
* Function Call and Print:
print(fibonacci(5)): Calls the fibonacci function with n=5 and prints the resulting tuple.

42. Create a tuple from user input.

In [7]:
user= tuple(input('Enter the List of names seperated by comma').split(','))

print(user, type(user))

Enter the List of names seperated by comma john,harry


('john', 'harry') <class 'tuple'>


Explanation:

* Used input() inbuilt function to get the input from user and used the split() with , as seperator then used the tuple() function to type cast it
* printing the variable user and and type of the variable 

43. Swap two elements in a tuple.

In [2]:
def swap_elements(tuple_, index1, index2):
    list_ = list(tuple_)
    list_[index1], list_[index2] = list_[index2], list_[index1]
    swapped_tuple = tuple(list_)
    return swapped_tuple

original_tuple = (1, 2, 3, 4, 5)
index_to_swap1 = 1
index_to_swap2 = 3

result_tuple = swap_elements(original_tuple, index_to_swap1, index_to_swap2)
print("Original Tuple:", original_tuple)
print("Tuple after swapping elements:", result_tuple)


Original Tuple: (1, 2, 3, 4, 5)
Tuple after swapping elements: (1, 4, 3, 2, 5)


Explanation : 

* Function Definition:
A function named swap_elements is defined to swap elements in a tuple.
* Tuple to List and Element Swap:
The tuple is converted to a list.
Elements at specified indices (index1 and index2) are swapped using tuple unpacking.
* List to Tuple and Return:
The list is converted back to a tuple (swapped_tuple).
The resulting tuple is returned.
* Example Usage:
An example tuple original_tuple is provided.
Indices (index_to_swap1 and index_to_swap2) are specified for element swapping.
* Function Call and Print:
The function is called with the example tuple and indices.
The original and resulting tuples are printed.

44. Reverse the elements of a tuple.

In [1]:
def reverse_tuple(tuple_):
    reversed_tuple = tuple_[::-1]
    return reversed_tuple

# Example usage
original_tuple = (1, 2, 3, 4, 5)
result_tuple = reverse_tuple(original_tuple)

# Print the original and reversed tuples
print("Original Tuple:", original_tuple)
print("Reversed Tuple:", result_tuple)

Original Tuple: (1, 2, 3, 4, 5)
Reversed Tuple: (5, 4, 3, 2, 1)


Explanation:

* Function Definition:
The reverse_tuple function takes a tuple as input and returns the reversed tuple.
* Tuple Reversal:
reversed_tuple = tuple_[::-1]: This line creates a new tuple (reversed_tuple) by using slicing to reverse the order of elements in the original tuple.
* Example Usage:
An example tuple original_tuple is provided.
* Function Call and Print:
The function is called with the example tuple.
The original and reversed tuples are printed.

45. Create a tuple of the first `n` powers of 2.

In [7]:
def powers(n):
    value=[]
    for i in range(1,n+1):
        value.append(2**i)
    return tuple(value)
n=3
print(powers(n))

(2, 4, 8)


Explanation:

* Function Definition:
A function named powers is defined, taking an integer n as its parameter.
* List Generation in a Loop:
Inside the function, a list named value is initialized. The function uses a for loop to iterate from 1 to n (inclusive).
For each iteration, it calculates the value of 2**i and appends it to the list value. This loop generates the first n powers of 2.
* Convert List to Tuple and Return:
After the loop, the function converts the list value to a tuple using tuple(value) and returns the resulting tuple.
* Example Usage:
An example with n = 3 is provided. This represents the number of powers of 2 you want to generate.
* Function Call and Print:
The function is called with the specified value of n, and the resulting tuple is assigned to the variable result_tuple.
The resulting tuple is printed.

46. Find the longest string in a tuple of strings.

In [27]:
tuple_=('jas', 'vijay','cinema', 'jasper')
max_= len(max(tuple_, key=lambda x: len(x)))
longest_string=tuple(i for i in tuple_ if len(i)==max_)
print('The longest strings in the tuple of string are :',longest_string)

The longest strings in the tuple of string are : ('cinema', 'jasper')


#Explanation:

* Initiating a variable tuple_ with string values
* max_length = len(max(tuple_, key=lambda x: len(x))):
The max() function is used to find the maximum element in the tuple_ based on the length of each string. The key=lambda x: len(x) specifies that the length of each string should be used for comparison.
max() returns the maximum string, and len() is then used to calculate the length of that string. The result is stored in the variable max_length.
* longest_strings = tuple(i for i in tuple_ if len(i) == max_length):
A generator expression is used to create a tuple (longest_strings) containing all the strings from tuple_ that have a length equal to the max_length.
The for i in tuple_ iterates over each element in tuple_, and if len(i) == max_length checks if the length of the string i is equal to the previously calculated maximum length (max_length).
The tuple is created using the tuple() constructor.
* print('The longest strings in the tuple of strings are:', longest_strings):
Finally, the code prints the message along with the tuple of longest strings.

47. Find the shortest string in a tuple of strings.

In [32]:
def short(tuple_):
    min_= len(min(tuple_, key=lambda x: len(x)))
    shortest_string=tuple(i for i in tuple_ if len(i)==min_)
    return shortest_string

tuple_=('jas', 'vijay','key', 'jasper')

print('The Shortest strings in the tuple of string are :',short(tuple_)) 


The Shortest strings in the tuple of string are : ('jas', 'key')


#Explanation:

* Function Definition:def short(tuple_): This line defines a function named short that takes a single argument, tuple_.
* Finding Minimum Length: The min() function finds the minimum element in the tuple_ based on the length of each string. The key=lambda x: len(x) specifies that the length of each string should be used for comparison. The length of the minimum string is then calculated using len(), and the result is stored in the variable min_length.
* Creating Tuple of Shortest Strings: A generator expression is used to create a tuple (shortest_strings) containing strings from tuple_ that have a length equal to the min_length.
The for i in tuple_ iterates over each element in tuple_, and if len(i) == min_length checks if the length of the string i is equal to the previously calculated minimum length (min_length).
The resulting strings are included in the tuple using the tuple() constructor.
* return shortest_strings: The function returns the tuple of shortest strings.
* Function Call and Print: The function is called with the provided tuple, and the result is printed, indicating the strings with the minimum length in the original tuple.

48. Create a tuple of the first `n` triangular numbers.

In [47]:
def triangular_(n):
    result= tuple( i*(i+1)//2 for i in range (1,5+1)) 
    return result
n=5
print("Tuple of the first", n, "triangular numbers:", triangular_(n))

Tuple of the first 5 triangular numbers: (1, 3, 6, 10, 15)


Explanation:
* Function Definition: Define a function named triangular_ that takes an argument n.

* Generating Tuple of Triangular Numbers: Generate a tuple (result) containing the first 5 triangular numbers using a list comprehension and the formula i*(i+1)//2 

* Returning the Result: Return the tuple (result) of the first 5 triangular numbers.

* Function Call and Print: Call the function with n = 5 and print the result.

49. Check if a tuple contains another tuple as a subsequence.

In [1]:
def is_subsequence(sub, main):
    for i in range(len(main) - len(sub) + 1):
        if main[i:i+len(sub)] == sub:
            return True
    return False

main_tuple = (1, 2, 3, 4, 5, 6)
sub_tuple = (3, 4, 5)

result = is_subsequence(sub_tuple, main_tuple)
print(result)

True


Explanation:
    
* Function Definition:
Define a function named is_subsequence that takes two tuples as arguments: sub (potential subsequence) and main (main tuple).
* terating Through the Main Tuple:
Use a for loop to iterate through the indices of the main tuple.
The loop runs from 0 to len(main) - len(sub) + 1 to cover possible starting indices for the subsequence check.
* Checking for Subsequence:
Within the loop, check if the slice of the main tuple from index i to i+len(sub) is equal to the sub tuple.
If true, it means that the elements of the sub tuple appear consecutively in the same order within the main tuple.
* Return True If Subsequence Found:
If a match is found, immediately return True, indicating that the sub tuple is a subsequence of the main tuple.
* Return False if No Subsequence Found:
If the loop completes without finding a match, return False, indicating that the sub tuple is not a subsequence of the main tuple.
* Finally calling the function by passing the sample main and sub tuples and printing the results

50. Create a tuple of alternating 1s and 0s of length `n`.

In [2]:
def create_alternating_tuple(n):
    alternating_sequence = [i % 2 for i in range(n)]
    result_tuple = tuple(alternating_sequence)# Convert the list to a tuple
    return result_tuple

n = 10  
result = create_alternating_tuple(n)
print(result)


(0, 1, 0, 1, 0, 1, 0, 1, 0, 1)


Explanation:

* Function Definition:
Define a function named create_alternating_tuple that takes an argument n.
* Generate Alternating Sequence:
Utilize a list comprehension to create a sequence (alternating_sequence) of alternating 1s and 0s based on the index i. The expression i % 2 ensures alternation between 0 and 1.
* Convert List to Tuple:
Convert the list (alternating_sequence) to a tuple (result_tuple) using the tuple() function.
* Return Resulting Tuple:
Return the resulting tuple containing alternating 1s and 0s.
* Providing n =10 and calling the function and stored it in variable result finally printing it
    

# Set Based Practice Problem :

1. Create a set with integers from 1 to 5.

In [6]:
integers ={1,2,3,4,5} # Use curly braces {} to create a set. Inside the braces, list the integers from 1 to 5, separated by commas.
print(integers) # printing the set of integers

{1, 2, 3, 4, 5}


2. Add an element to a set.

In [11]:
set_={1,2,3,4,5} # Created a set with list of integers from 1-5
set_.add(6) # using the add method and 
print(set_)

{1, 2, 3, 4, 5, 6}


Explanation: 
* Created a set with list of integers from 1-5 
* Using the inbuilt function add() to add an element 
* printing the set_

3. Remove an element from a set.

In [12]:
set_={1, 2, 3, 4, 5, 6}
set_.remove(6)
set_

{1, 2, 3, 4, 5}

Explanation: 
* Created a set with list of integers from 1-6 
* Using the inbuilt function remove() to add an element from this set, it only remove if the element is present else it will raise error.
* printing the set_

4. Check if an element exists in a set.

In [14]:
set_={1, 2, 3, 4, 5, 6}
element= 3
if element in set_:
    print('Element exists')
else:
    print("Element doesn't exists")

Element exists


Explanation:

* Created a set of 1-6 integers with variable set_ 
* Initiated an element which want to check in the set_variable
* Used the If else statement and in keyword to check if the element in the set_ this will return the bolean True or false, if true it will print exlement exists else print element doesn't exists.

5. Find the length of a set without using the `len()` function.

In [29]:
set_={1,3,4,5,6,7,8}
length=0
for i in set_:
    length+=1
    
print('The length of the set_ is', length)

The length of the set_ is 7


Explanation:

* Created a variable names set_ consists of integers in set type.
* Initiated a variable length with 0 as value for later purpose.
* In for loop iterate over all the elements in set and for every iteration adding 1 to the length variable.

6. Clear all elements from a set.

In [31]:
set_={1,3,4,5,6,7,8}
set_.clear()
print(set_)

set()


Explanation:

* Created a set with intergers.
* Used the inbuilt clear function() and cleared all the elements in set.
* printing the set_ variable 


7. Create a set of even numbers from 1 to 10.

In [5]:
even_numbers_set= {i for i in range(1,10) if i % 2==0}
print('Set of even numbers from 1-10 are', even_numbers_set)

Set of even numbers from 1-10 are {8, 2, 4, 6}


Explanation: 
* Used set comprehension to generate a set named even_numbers_set.
* The comprehension iterates through numbers from 1 to 10 (range(1, 10)) and includes only those numbers that are even (if i % 2 == 0).
* Printing the variable even_numbers_set along with the text  Set of even numbers from 1-10 are.

8. Create a set of odd numbers from 1 to 10.

In [4]:
odd_numbers_set = {i for i in range(1, 11) if i % 2 != 0}
print('Set of odd numbers from 1-10 are', odd_numbers_set)

Set of odd numbers from 1-10 are {1, 3, 5, 7, 9}


Explanation: 
* Used set comprehension to generate a set named odd_numbers_set.
* The comprehension iterates through numbers from 1 to 10 (range(1, 10)) and includes only those numbers that are even (if i % 2 != 0).
* Printing the variable odd_numbers_set along with the text Set of odd numbers from 1-10 are.

9. Find the union of two sets.

In [7]:
set1={1,2,3,4,5}
set2={6,7,8,9,10}
union_set= set1.union(set2)
print('Union Set :',union_set)

Union Set : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


Exlanation:

* Created two sets set1 and set2 with list of integers and used the set operation function union() 
* Print the union_set with text Union Set:

10. Find the intersection of two sets.

In [9]:
set1={1,2,3,4,5}
set2={2,3,5,6,7,8,9,10}
intersection_set= set1.intersection(set2)
print("Intersection set: ",intersection_set)

Intersection set:  {2, 3, 5}


Exlanation:

* Created two sets set1 and set2 with list of integers
* The intersection() method is used to find the intersection of the two sets. This method returns a new set containing common elements from both sets.
* Print the intersection_set with text intersection Set:

11. Find the difference between two sets.

In [12]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

difference_set = set1.difference(set2)
print("difference set: ",difference_set)

difference set:  {1, 2}


Exlanation:

* Created two sets set1 and set2 with list of integers
* The difference() method is used to find the difference between set1 and set2. This method returns a new set containing elements that are present in set1 but not in set2.
* Print the difference_set with text difference Set:

12. Check if a set is a subset of another set.

In [4]:
set1 = {1, 2, 3, 4,5, 6}
set2 = {3,4,5}

if set2.issubset(set1):
    print('Set2 is a subset of set1.')
else:
    print('Set2 is not a subset of set1.')


Set2 is a subset of set1.


Exlanation:

* Created two sets set1 and set2 with list of integers
* The issubset() method is used to check if set2 is a subset of set1. This method returns True if every element of the set is present in the other set, and False otherwise. Hence used the If else condition and if the statement is true it will print set2 is subset else it not.


13. Check if a set is a superset of another set.

In [9]:
set1 = {1, 2}
set2 = {1, 2, 3, 4}

if set2.issuperset(set1):
    print('Set 2 is super set of set1')
else:
    print('Set 2 is not super set of set1')



Set 2 is super set of set1


Exlanation:

* Created two sets set1 and set2 with list of integers
* The issuperset() method is used to check if set2 is a superset of set1. This method returns True if every element of the other set is present in the set, and False otherwise. Hence used the If else condition and if the statement is true it will print set2 is superset else it not.


14. Create a set from a list.

In [19]:
list_=[1,3,4,5,6,4]
set_=set(list_)
print(f'''List :{list_},
set from list : {set_}''')


List :[1, 3, 4, 5, 6, 4],
set from list : {1, 3, 4, 5, 6}


Explanation:
* Created a list with list of integers
* Used set() constructor to convert the list_ into a set. This automatically removes duplicate elements, creating a set with only unique elements. The resulting set is stored in the variable set_.
- Finally, we print both the original list and the set obtained from the list using print() statements.

15. Convert a set to a list.

In [1]:
set_={1,2,3,4,5}
list_=list(set_)
print(f''' Set :{set_}
converted to list :{list_}''')

 Set :{1, 2, 3, 4, 5}
converted to list :[1, 2, 3, 4, 5]


Explanation:
* Created a set with list of integers
* Used list() constructor to convert the set_ into a list. 
* Finally, we print both the original set and the list obtained from the set using print() statements.

16. Remove a random element from a set.

In [2]:
import random 

my_set = {1, 2, 3, 4, 5}

print("Original set:", my_set)

random_element = random.choice(list(my_set))

my_set.remove(random_element)# Remove the chosen random element from the set using the remove() method

print("Updated set after removing", random_element, ":", my_set)

Original set: {1, 2, 3, 4, 5}
Updated set after removing 5 : {1, 2, 3, 4}


Explanation:
* Import random module
* random.choice(list(my_set)):
Convert the set to a list using list(my_set).
Use random.choice() to choose a random element from the list.
* my_set.remove(random_element):
Remove the chosen random element from the set using the remove() method.
* Print the Original and Updated Sets:
Print the original set before removing the random element.
Print the updated set after removing the random element.

17. Pop an element from a set.

In [5]:
my_set = {1, 2, 3, 4, 5}
popped_element = my_set.pop()

print("Popped Element:", popped_element)
print("Updated Set:", my_set)

Popped Element: 1
Updated Set: {2, 3, 4, 5}


Explanation:

* Created a set with list of integers
* used the pop() method it removes and returns an arbitrary element from the set.
* printing both the removed element and updated set

18. Check if two sets have no elements in common.

In [8]:
set_1={1,2,3,4,5}
set_2={6,7,8,9,10}

common_elements= set_1.intersection(set_2)
if not common_elements:
    print('No Common Elements')
else: 
    Print('Common elements found',common_elements)

No Common Elements


Explanation:
    
* Created two sets set_1 and set_2 with different elements 
* Used the intersection() method to find the common elements in the sets and stored the return elements in the variable common_elements
* If the common_elements is empty of not having any elements printing the statement no common elements else printing the statement common elements found with common elements value.

19. Find the symmetric difference between two sets.

In [12]:
set_1={1,2,3,4,5,6,7}
set_2={6,7,8,9,10}

symmetric_difference= set_1.symmetric_difference(set_2)
print('Symmetric difference between set_1 and set_2: ',symmetric_difference)

Symmetric difference between set_1 and set_2:  {1, 2, 3, 4, 5, 8, 9, 10}


Explanation:

* Created two sets set_1 and set_2 with difference elements and some common elements
* Used the symmetric_difference () inbuilt function this will return the elements that are unique to each set, excluding those that are common to both sets.
* Printing the statement with the symmetric_difference variable

20. Update a set with elements from another set.

In [17]:
set_1={1,2,3,4,5,6,7}
set_2={6,7,8,9,10}

set_1.update(set_2)
print('Updated set: ',set_1)

Updated set:  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


Explanation:

* Created two sets set_1 and set_2 with integers
* used the update() inbuilt function and updated the set_2 with the set_1 it will remove any duplicate and update the unique values
* Printing the set_1

21. Create a set of the first 5 prime numbers.

In [8]:
def prime(number):
    if number ==1:
        return False
    for i in range(2,int(number**0.5) +1):
        if number %i ==0:
            return False
    return True

def n_prime(n):
    prime_=set()
    number=2
    while len(prime_)<n:
        if prime(number):
            prime_.add(number)
        number+=1
    return prime_

n=5
print(f'The first {n} prime numbers are { n_prime(n)}')       


The first 5 prime numbers are {2, 3, 5, 7, 11}


Explanation:

* prime(number) function:
Checks if a given number is prime using a loop that iterates from 2 to the square root of the number.
Returns True if the number is prime and False otherwise.
* n_prime(n) function:
Generates a set (prime_set) containing the first n prime numbers.
Utilizes the prime() function to determine if a number is prime before adding it to the set.
Uses a while loop to continue adding prime numbers until the set contains n elements.
* Main Code:
Specifies the value of n (in this case, 5) to indicate the number of prime numbers to generate.
Prints the first n prime numbers using the n_prime function.

22. Check if two sets are identical.

In [9]:
set_1={1,2,3,4}
set_2={1,2,3,4}

if set_1==set_2:
    print('Identical sets')
else:
    print('Not Identical Sets')

Identical sets


Explanation:

* Defined two sets set_1 and set_2 with same set of integeres
* used the = operator and use the if condition to check both the sets are equal if its equal it will print identical sets else not identical

23. Create a frozen set.

In [1]:
my_set = {1, 2, 3, 4, 5}

my_frozen_set = frozenset(my_set)

# Print both sets
print("Regular Set:", my_set)
print("Frozen Set:", my_frozen_set)

Regular Set: {1, 2, 3, 4, 5}
Frozen Set: frozenset({1, 2, 3, 4, 5})


Explanation:

Created an ordinary set with integers
*  Converted the ordinary set into frozen set using frozenset() constructor, now this set will be immutable.
* Printing both the original and frozenset

24. Check if a set is disjoint with another set.

In [6]:
set_1={1,2,3,4}
set_2={5,6,7,8,9}
is_disjoin= set_1.isdisjoint(set_2)
print("Are the sets disjoint?",is_disjoin)

Are the sets disjoint? True


Explanation:

- We start by defining two sets, set_1 and set_2, which contain different elements. You can modify these sets with the elements you want to use for the check.
- The isdisjoint() method is called on set_1 and is passed set_2 as an argument. This method checks whether the sets have any elements in common.
- The result of the disjointness check is stored in the is_disjoin variable. If the sets are disjoint, disjoint_status will be True, and if they are not disjoint, it will be False.
- Finally, we use the print() function to display the result. It will print a message indicating whether the sets are disjoint or not based on the value of the disjoint_status variable.

25. Create a set of squares of numbers from 1 to 5.

In [12]:
def squares(start_range, end_range):
    n_squares={ i**2 for i in range(start_range,end_range+1)}
    return n_squares
start_range, end_range= 1,5
print(f'Set of squares numbers from {start_range}-{end_range} {squares(start_range, end_range)}')

Set of squares numbers from 1-5 {1, 4, 9, 16, 25}


Explanation:

* Created a function with two input parameters squares(start_range, end_range)
* using the set comprehension insdide that loop the start and end range getting from the parameters and using the exponential operation ** to square root it and storing it to n_squares variable.
* Return the n_squares
* initializing the start and end range then printing the text and call the function using f string.

26. Filter out all even numbers from a set.

In [13]:
set_={1,2,3,4,5,6,7,8,9,12,14,16}
even_numbers= {i for i in set_ if i %2==0}
print("Even numbers from set : ",even_numbers)

Even numbers from set :  {2, 4, 6, 8, 12, 14, 16}


Explanation:
    
* Created a set variable with list of integers
* The set comprehension {i for i in set_ if i % 2 == 0} iterates through each element in set_.It includes only those elements (i) that are even (i.e., i % 2 == 0 is True).
* Printing the variable even_numbers which contains the even numbers from the set

27. Multiply all elements in a set by 2.

In [16]:
set_={1,2,3,4,5}
multiplied_set= {i*2 for i in set_}
print(f'''Original set: {set_}
multiplied by 2: {multiplied_set}''')

Original set: {1, 2, 3, 4, 5}
multiplied by 2: {2, 4, 6, 8, 10}


Explanation:

* Set Definition:
set_ is a set containing integers.
* Set Comprehension:
The set comprehension {i * 2 for i in set_} iterates through each element in set_.
It includes the doubled value of each element in the new set.
* Result Printing:
The original set and the set with elements multiplied by 2 are printed using an f-string.

28. Create a set of random numbers.

In [24]:
import random
random.randint(1,100)
n= 5
random_set=set()
while len(random_set)<n:
    random_set.add(random.randint(1,100))
print(f'Random set of numbers :{random_set}')

Random set of numbers :{64, 9, 78, 14, 91}


Explanation:

* Import Random Module:
import random: Imports the random module for generating random numbers.
* Generate a Single Random Integer:
random_integer = random.randint(1, 100): Generates a single random integer between 1 and 100 (inclusive).
* Specify the Number of Elements:
n = 5: Specifies the desired number of elements in the random set.
* Create an Empty Set:
random_set = set(): Initializes an empty set to store unique random integers.
* Generate Random Set:
while len(random_set) < n:: Uses a while loop to add random integers to the set until it reaches the specified size n.
random_set.add(random.randint(1, 100)): Adds a random integer between 1 and 100 to the set.
* Print Result:
print(f'Random set of numbers: {random_set}'): Prints the final random set of numbers.

29. Check if a set is empty.

In [25]:
set_1= {1,2,3,4}
set_2=set()
if not set_1:
    print("set_1 is empty")
else:
    print('Set_1 is not empty')
if not set_2:
    print('set_2 is empty')
else:
    print('set_2 is not empty')

Set_1 is not empty
set_2 is empty


Explanation:
 
* Set Definitions:
set_1 = {1, 2, 3, 4}: Defines a non-empty set with elements.
set_2 = set(): Creates an empty set.
* Check for Empty Sets:
if not set_1:: Checks if set_1 is empty. If it is, it prints "set_1 is empty"; otherwise, it prints 'set_1 is not empty'.
if not set_2:: Checks if set_2 is empty. If it is, it prints "set_2 is empty"; otherwise, it prints 'set_2 is not empty'.

30. Create a nested set (hint: use frozenset).

In [30]:
nested_set={frozenset({1,2,3}),frozenset({3,4,5}),frozenset({5,6,7})}
nested_set

{frozenset({1, 2, 3}), frozenset({5, 6, 7}), frozenset({3, 4, 5})}

Explanation:

* Frozensets Creation:
frozenset({1, 2, 3}), frozenset({3, 4, 5}), and frozenset({5, 6, 7}): Create three frozensets, each representing a subset of integers.
* Nested Set Creation:
{frozenset({1, 2, 3}), frozenset({3, 4, 5}), frozenset({5, 6, 7})}: Create a set (nested_set) that contains the three frozensets created in the previous step.
* Printing the Nested Set:
print("Nested set:", nested_set): Print the contents of the nested_set.

31. Remove an element from a set using the discard method.

In [34]:
set_={1,2,3,4}
print('original set: ',set_)
set_.discard(2)
print('after discard: ',set_)

original set:  {1, 2, 3, 4}
after discard:  {1, 3, 4}


Explanation:
   
* Created a set with random integers
* printing the original set to show the difference after discard
* using the discard() method and removing the element want to remove passing it inside the discard(2) function. If the element is present it will remove else it will run without throwing any error.
* printing the set_1 now to show the difference

32. Compare two sets.

In [46]:
set_1 = {1, 2, 3, 4, 5}
set_2 = {3, 4, 5, 6, 7}

print("Set 1:", set_1)
print("Set 2:", set_2)

print('\nResults of general comparison operators:')
# Compare sets using equality (==)
if set_1 == set_2:
    print("The sets are equal")
else:
    print("The sets are not equal")

# Compare sets using other operators
if set_1 < set_2:
    print("set_1 is a proper subset of set_2")
elif set_1 > set_2:
    print("set_1 is a proper superset of set_2")
else:
    print("The sets have some common elements")
    
# Set operations

# Check if set1 is a subset of set2
is_subset = set_1.issubset(set_2)

# Check if set2 is a subset of set1
is_superset = set_1.issuperset(set_2)

# Find the intersection of the sets
intersection = set_1.intersection(set_2)

# Find the union of the sets
union = set_1.union(set_2)

# Find the elements that are in set1 but not in set2
difference1 = set_1.difference(set_2)

# Find the elements that are in set2 but not in set1
difference2 = set_2.difference(set_1)

# Step 3: Print the results
print('\nResults of Set operations:')
print("Is set1 a subset of set2?", is_subset)
print("Is set2 a subset of set1?", is_superset)
print("Intersection:", intersection)
print("Union:", union)
print("Elements in set1 but not in set2:", difference1)
print("Elements in set2 but not in set1:", difference2)

Set 1: {1, 2, 3, 4, 5}
Set 2: {3, 4, 5, 6, 7}

Results of general comparison operators:
The sets are not equal
The sets have some common elements

Results of Set operations:
Is set1 a subset of set2? False
Is set2 a subset of set1? False
Intersection: {3, 4, 5}
Union: {1, 2, 3, 4, 5, 6, 7}
Elements in set1 but not in set2: {1, 2}
Elements in set2 but not in set1: {6, 7}


Explanation:
General operators:
* set_1 == set_2: Checks if the two sets are equal.
* set_1 < set_2: Checks if set_1 is a proper subset of set_2.
* set_1 > set_2: Checks if set_1 is a proper superset of set_2.

Set operations:
 - issubset() checks if set1 is a subset of set2.
  - issuperset() checks if set1 is a superset of set2.
  - intersection() finds the common elements between the sets.
  - union() finds the combined set of unique elements from both sets.
  - difference() finds the elements that are in the first set but not in the second set, and vice versa.
-  print out the original sets, the comparison results, the intersection, the union, and the differences.


33. Create a set from a string.


In [51]:
string_='Hello world'
myset=set(string_)
myset

{' ', 'H', 'd', 'e', 'l', 'o', 'r', 'w'}

Explanation:
- Start by defining an input string "Hello world".
- We use the set() constructor to create a set named myset from the characters present in the input string. The set() constructor automatically eliminates duplicate characters since sets don't allow duplicates.
- Finally, we print the resulting set using the print() function. This will output a set containing the unique characters from the input string.

34. Convert a set of strings to a set of integers.

In [56]:
string_set = {"123", "456", "789"}
converted_int_set= {int(i) for i in string_set}
print(f'''String set: {string_set}
integer set: {converted_int_set}''')

String set: {'456', '123', '789'}
integer set: {456, 123, 789}


Explanation:

* String Set Definition:
string_set = {"123", "456", "789"}: Defines a set of strings.
* Set Comprehension for Conversion:
converted_int_set = {int(i) for i in string_set}: Creates a new set (converted_int_set) by using a set comprehension to convert each string element in string_set to an integer using the int() function.
* Printing the Results:
print(f'String set: {string_set}\nInteger set: {converted_int_set}'): Prints the original string set and the set of converted integers using an f-string.

35. Convert a set of integers to a set of strings.

In [3]:
integer_set= {456, 123, 789}
converted_str_set= {str(i) for i in integer_set}
print(f'''Integer set: {integer_set}
String set: {converted_str_set}''')

Integer set: {456, 123, 789}
String set: {'789', '456', '123'}


Explanation:

* Integer Set Definition:
integer_set = {456, 123, 789}: Defines a set of integers.
* Set Comprehension for Conversion:
converted_str_set = {str(i) for i in integer_set}: Creates a new set (converted_str_set) by using a set comprehension to convert each integer element in integer_set to a string using the str() function.
* Printing the Results:
print(f'Integer set: {integer_set}\nString set: {converted_str_set}'): Prints the original integer set and the set of converted strings using an f-string.

36. Create a set from a tuple.

In [5]:
tuple_=(1,2,3,4,5,4)
set_convert=set(tuple_)
print(set_convert)

{1, 2, 3, 4, 5}


Explanation:
    
* Created a tuple with integers from 1-5 with one duplicate 4
* Used the set() constructor to convert the tuple into set since set doesn't have duplicates duplicates will be removed and stored it in the variable set_convert
* printing the variable set_convert

37. Convert a set to a tuple.

In [6]:
set_={1, 2, 3, 4, 5}
tuple_convert=tuple(set_)
print(tuple_convert)

(1, 2, 3, 4, 5)


Explanation:
    
* Created a set with integers from 1-5
* used the tuple() constructor to convert the set into tuple and stored it in variable tuple_convert.
* printing the variable tuple_convert to show the result in tuple.

38. Find the maximum value in a set.

In [15]:
my_set = {15, 7, 22, 13, 8}
max_value=0
for i in my_set:
    if i>max_value:
        max_value=i
print(f'Maximum value in {my_set} is {max_value}')

Maximum value in {22, 7, 8, 13, 15} is 22


Explanation:

* my_set = {15, 7, 22, 13, 8}: Defines a set with elements.
* max_value = 0: Initializes max_value to 0.
* for i in my_set:: Iterates over each element in the set.
* if i > max_value:: Checks if the current element i is greater than the current max_value.
* max_value = i: If i is greater than the current max_value, updates max_value to i.
* print(f'Maximum value in {my_set} is {max_value}'): Prints the result using an f-string.

39. Find the minimum value in a set.

In [21]:
my_set = {15, 7, 22, 13, 8}
min_value=None
for i in my_set:
    if min_value is None or i< min_value:
        min_value=i
print(f'Minimum value in {my_set} is {min_value}')

Minimum value in {22, 7, 8, 13, 15} is 7


Explanation:

* my_set = {15, 7, 22, 13, 8}: Defines a set with elements.
* min_value = None: Initializes min_value to None.
* for i in my_set:: Iterates over each element in the set.
* if min_value is None or i < min_value:: Checks if min_value is None or if the current element i is less than the current min_value.
* min_value = i: If the conditions are met, updates min_value to i.
* print(f'Minimum value in {my_set} is {min_value}'): Prints the result using an f-string.

40. Create a set from user input.

In [26]:
user_input = input("Enter elements separated by commas: ")
user_set = set(user_input.split(','))

print(f'The created set from user input: {user_set}')


Enter elements separated by commas:  jas,ajay,edwin


The created set from user input: {'ajay', 'jas', 'edwin'}


Explanation:

* user_input = input("Enter elements separated by commas: "): Prompts the user to enter elements separated by commas.
* user_set = set(user_input.split(',')): Converts the input string into a set. The split(',') method is used to split the input string into a list of elements using commas as separators.
* print(f'The created set from user input: {user_set}'): Displays the resulting set.

41. Check if the intersection of two sets is empty.

In [3]:
set_1={1,2,3,4}
set_2={5,6,7,8}
intersection_result = set_1.intersection(set_2)
if not intersection_result:
    print("The intersection of the two sets is empty.")
else:
    print("The intersection of the two sets is not empty.")

The intersection of the two sets is empty.


Explanation:

* set_1 = {1, 2, 3, 4}: Defines the first set.
* set_2 = {5, 6, 7, 8}: Defines the second set.
* intersection_result = set_1.intersection(set_2): Finds the intersection of set_1 and set_2.
* if not intersection_result:: Checks if the intersection is empty using the not keyword.
* print("The intersection of the two sets is empty."): Prints a message if the intersection is empty.
* else:: Executes if the intersection is not empty.
* print("The intersection of the two sets is not empty."): Prints a message indicating that the intersection is not empty.

42. Create a set of the first 5 Fibonacci numbers.

In [20]:
def fibonacci(n):
    fibbi=[0,1]
    while len(fibbi) < n+1:
        fibbi.append(fibbi[-1]+fibbi[-2])
    return set(fibbi)
        
print('First 5 fibonacci numbers in set : ',fibonacci(5))

First 5 fibonacci numbers in set :  {0, 1, 2, 3, 5}


Explanation:

* def fibonacci(n): Defines a function named fibonacci that takes an argument n.
* fibbi = [0, 1]: Initializes the list with the first two Fibonacci numbers.
* while len(fibbi) < n + 1:: Continues adding Fibonacci numbers to the list until it reaches the desired length n + 1.
* fibbi.append(fibbi[-1] + fibbi[-2]): Computes the next Fibonacci number by summing the last two elements.
* return set(fibbi): Converts the list into a set and returns it.
* print('First 5 Fibonacci numbers in set:', fibonacci(5)): Calls the function to generate the first 5 Fibonacci numbers and prints the resulting set.

43. Remove duplicates from a list using sets.

In [24]:
original_list = [1, 2, 3, 1, 4, 2, 5, 6, 3]

unique_list = list(set(original_list))

print(f'Original List: {original_list}')
print(f'List with Duplicates Removed: {unique_list}')


Original List: [1, 2, 3, 1, 4, 2, 5, 6, 3]
List with Duplicates Removed: [1, 2, 3, 4, 5, 6]


Explanation:

* original_list = [1, 2, 3, 1, 4, 2, 5, 6, 3]: Defines the original list with duplicates.
* unique_list = list(set(original_list)): Converts the original list to a set, removing duplicates, and then converts it back to a list.
* print(f'Original List: {original_list}'): Prints the original list.
* print(f'List with Duplicates Removed: {unique_list}'): Prints the list with duplicates removed.

44. Check if two sets have the same elements, regardless of their count.

In [1]:
def have_same_elements(set1, set2):
    sorted_list1 = sorted(list(set1))
    sorted_list2 = sorted(list(set2))
    return sorted_list1 == sorted_list2

set1 = {1, 2, 3, 2, 1}
set2 = {3, 1, 2}

result = have_same_elements(set1, set2)

# Print the result
if result:
    print("The sets have the same elements.")
else:
    print("The sets do not have the same elements.")

The sets have the same elements.


Explanation:

* def have_same_elements(set1, set2): Defines a function that takes two sets as parameters.
* sorted_list1 = sorted(list(set1)): Converts set1 to a sorted list.
* sorted_list2 = sorted(list(set2)): Converts set2 to a sorted list.
* return sorted_list1 == sorted_list2: Checks if the sorted lists are equal, indicating whether the sets have the same elements.
* Example sets:
* set1 = {1, 2, 3, 2, 1}: Contains duplicates and is not in sorted order.
* set2 = {3, 1, 2}: Is in a different order but has the same elements.
* result = have_same_elements(set1, set2): Calls the function with the example sets to check if they have the same elements.
* Prints the result based on whether the sets have the same elements or not.

45. Create a set of the first `n` powers of 2.

In [8]:
def powers_of_2(n):
    return {2 ** i for i in range(n)}

n = 5
result_set = powers_of_2(n)

print(f'The first {n} powers of 2: {result_set}')

The first 5 powers of 2: {1, 2, 4, 8, 16}


Explanation:

* def powers_of_2(n): Defines a function that takes an argument n.
* {2 ** i for i in range(n)}: Uses a set comprehension to generate a set containing the first n powers of 2. 2 ** i calculates 2 raised to the power of i for each i in the range from 0 to n-1.
* n = 5: Example value for n, indicating the number of powers of 2 to generate.
* result_set = powers_of_2(n): Calls the function to create the set of the first n powers of 2.
* print(f'The first {n} powers of 2: {result_set}'): Prints the resulting set.

46. Find the common elements between a set and a list.

In [22]:
def common_elements(set_, list_):
    common_elements=set_.intersection(set(list_))
    return f"Common elements: {common_elements}"

my_set = {3, 7, 9, 12, 15}
my_list = [7, 12, 5, 9]
print(common_elements(my_set, my_list))

Common elements: {9, 12, 7}


Explanation:

* def common_elements(set_, list_): Defines a function that takes a set and a list as parameters.
* common_elements = set_.intersection(set(list_)): Finds the intersection (common elements) between the set and the list.
* return f"Common elements: {common_elements}": Returns a formatted string indicating the common elements.
* my_set = {3, 7, 9, 12, 15}: Example set.
* my_list = [7, 12, 5, 9]: Example list.
* print(common_elements(my_set, my_list)): Calls the function to find and print the common elements.

47. Create a set of the first `n` triangular numbers.

In [28]:
def generate_triangular_numbers(n):
    triangular_numbers = set()  
    for i in range(1, n + 1):
        triangular_number = i * (i + 1) // 2  
        triangular_numbers.add(triangular_number)  
    return triangular_numbers

n = int(input("Enter the value of n: "))

triangular_set = generate_triangular_numbers(n)

print(f"The set of the first {n} triangular numbers is:", triangular_set)

Enter the value of n:  5


The set of the first 5 triangular numbers is: {1, 3, 6, 10, 15}


Explanation:

* def generate_triangular_numbers(n): Defines a function that takes an argument n and generates a set of the first n triangular numbers.
* triangular_numbers = set(): Initializes an empty set to store the triangular numbers.
* for i in range(1, n + 1):: Iterates through the range from 1 to n (inclusive) to calculate each triangular number.
* triangular_number = i * (i + 1) // 2: Calculates the ith triangular number using the formula.
* triangular_numbers.add(triangular_number): Adds the calculated triangular number to the set.
* return triangular_numbers: Returns the set of triangular numbers.
* n = int(input("Enter the value of n: ")): Takes user input for the value of n.
* triangular_set = generate_triangular_numbers(n): Calls the function to generate the set of triangular numbers.
* print(f"The set of the first {n} triangular numbers is:", triangular_set): Prints the resulting set.

48. Check if a set contains another set as a subset.

In [29]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4}

is_subset = set2.issubset(set1)

if is_subset:
    print("set2 is a subset of set1")
else:
    print("set2 is not a subset of set1")

set2 is a subset of set1


Explanation:

* set1 = {1, 2, 3, 4, 5}: Defines a set named set1 containing elements 1, 2, 3, 4, and 5.
* set2 = {3, 4}: Defines another set named set2 containing elements 3 and 4.
* is_subset = set2.issubset(set1): Uses the issubset method to check if set2 is a subset of set1. The result (True or False) is stored in the variable is_subset.
* if is_subset:: Checks if is_subset is True.
* print("set2 is a subset of set1"): Prints a message indicating that set2 is a subset of set1 if the condition is True.
* else:: Executes if is_subset is False.
* print("set2 is not a subset of set1"): Prints a message indicating that set2 is not a subset of set1.

49. Create a set of alternating 1s and 0s of length `n`.

In [32]:
def create_alternating_set(n):
    return {i % 2 for i in range(n)}

n = 5
alternating_set = create_alternating_set(n)

print(f'The set of alternating 1s and 0s of length {n}: {alternating_set}')

The set of alternating 1s and 0s of length 5: {0, 1}


Explanation:

* def create_alternating_set(n): Defines a function that takes an argument n.
* {i % 2 for i in range(n)}: Uses a set comprehension to generate a set of alternating 1s and 0s. The expression i % 2 results in 0 when i is even and 1 when i is odd.
* n = 5: Example value for n, indicating the length of the set.
* alternating_set = create_alternating_set(n): Calls the function to create the set of alternating 1s and 0s.
* print(f'The set of alternating 1s and 0s of length {n}: {alternating_set}'): Prints the resulting set. since sets doesn't have duplicates only two elements will be shown

50. Merge multiple sets into one.

In [34]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set3 = {5, 6, 7}

merged_set = set1.union(set2, set3)

print("Merged Set:", merged_set)

Merged Set: {1, 2, 3, 4, 5, 6, 7}


Explanation:

* set1 = {1, 2, 3}, set2 = {3, 4, 5}, set3 = {5, 6, 7}: Defines three sets with different elements.
* merged_set = set1.union(set2, set3): Uses the union method to merge the three sets. The union method can take multiple sets as arguments and returns a new set containing all unique elements from the specified sets.
* print("Merged Set:", merged_set): Prints the resulting merged set.